### ISSUE TITLE
A shortcut to remove all cents.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Main#1039]
@OriRoth @EliaTraore @zahimizrahi @tomnof: FYI.

IMHO: the key should do it for everything in the file. What do people think?

**Comment by OriRoth** [comment]
If you have other relevant suggestions, please share them.

**Comment by yossigil** [comment]
@EliaTraore @zahimizrahi @tomnof: any key you prefer?

**Comment by OriRoth** [comment]
What about a global renaming tool? For various, user defined renaming jobs, such as:
`retVal, returnValue, result, $` ==> `ret`
`temp, tmp` ==> `__`
And will also offer regular Spartanizer renaming abilities, such as name simplifications.
Anyone interested?

**Comment by EliaTraore** [comment]
I think removing cents from the whole file with a few clicks is a bit too drastic, since you could end up changing methods you didn't intend to. But if the shourtcut would only remove the cent in the function you're in or in a marked area of code that could actually be nice :smile: 

And @OriRoth the jobs sounds like a good way to keep the code consistent. We would actually use that since we tend to have a lot of mixup when it comes to naming things like ID vs Id (as yogi already knows lol)

**Comment by yossigil** [comment]
I thought of a key that would remove/insert cents globally. This is pretty easy as cents have a well defined semantics: use a cent for a variable which is:

1. The only variable defined its namespace.
2. The namespace has no inner namespace.

So, one click is an option.

I think @OriRoth  is right. We need a global renaming tool that would apply things like:

- Standard (full) names of fields of a class.
- Standard cent as defined above.
- Name return variable to dollar
- Abbreviate John Doe parameters.
- Identify symmetrical variables and name them x1 x2 

All this should be configurable. I trust 90% of variables will fall into standard names. Perhaps @dormaayan  may take this as a research issue: do we need names for variables at all?


1.

**Comment by dormaayan** [comment]
@yossigil : Seems intresting, do you want that I will start form something specific ?

**Comment by yossigil** [comment]
Yes, make a wiki page regarding the naming rules.

**Comment by dormaayan** [comment]
See:
https://github.com/SpartanRefactoring/Spartanizer/wiki/Naming-Rules

Im currently edit it and think about more naming rules.

**Comment by ravivos** [comment]
all process of the expander that will be called when using this shortcut is documented in #979

**Comment by yossigil** [comment]
This can make an important part of the athenizer @ravivos

**Comment by dormaayan** [comment]
@yossigil :
Now we can configure both centification and dollarization
and also, pressing Ctrl+Alt+E we  change all centifications to 'param' and also the opposite.
