### ISSUE TITLE
Auto-generation of names

### ISSUE THREAD

**Issue by mdoron** [SpartanRefactoring/Main#1044]
Every expander using the environment @yossigil wrote would finally want to generate names for new variables. 
We should create a utility which generates this names.
Possible behavior: 
I don't care what is the name of the variable, then after
```
String name1 = Generate.varname();
```
name1 == "__tmp1"
For the next run of this utility we will get "__tmp2", etc.
If I care about the name of the variable, I will be able to write code like
```
String name2 = Generate.varname().from("baseString");
```
or maybe just
```
String name2 = Generate.varname("baseString");
```
and then name2 will hold "__baseString"
or if it's already taken "__baseString1", etc.

Since there are finite number of variable in the program, this utility will not run endlessly.

@yossigil, Do we have something like this in "Environment"? I haven't noticed anything like it.

**Comment by yossigil** [comment]
No, the environment does not offer this service yet. The plan is to generate meaningful names. Based on types, and then count up. Best to implement a function to generate suggestions based on type.
```java
Iterable<String>  candidateNames(Type t) {
...
}
```
also, see package `nominal`

@dormaayan fyi

**Comment by ravivos** [comment]
What's up with this?
URGENT
p.s it has no milestone, please add yours
for now I label it as 2.8

**Comment by mdoron** [comment]
By "Finished" I mean that there is no more that I can do without external help (@yossigil).
I used `type` (Yossi's class), but it is not ideal. I tried to use `.nominal.namer` but in order to do so I had to extract `Type` from `expression`, which is an open question right now...

**Comment by mdoron** [comment]
Okay, I finally understand what suppose to be here, and implemented. This was so confusing :S
But now it's okay so nevermind

**Comment by yossigil** [comment]
I think you should have used namer.components, not shorten

**Comment by mdoron** [comment]
@yuvalsimon: FYI, I added the functions you needed.

**Comment by yuvalsimon** [comment]
@mdoron Ok thanks. Add also search for switch statement. multiple statements could be under Block statement and also under switch statement (and maybe some other types, I didn't check).

**Comment by yuvalsimon** [comment]
@mdoron I added the switch too, alright? It can have multiple statements as block does.

**Comment by yuvalsimon** [comment]
I reverted my last commit because I'm not sure where else you assumed the node is a block and not switch statement. The implementation of _getScopeNamespace_ should be something like in https://github.com/SpartanRefactoring/Spartanizer/commit/fd4b1b9906a729769873e369ddf20eecac3475f4 (which considers switch statement), but I noticed for example the function below it also needs to be changed to treat switch statement (maybe there are more kinds of statements containing multiple statements property, I did not check)

**Comment by yuvalsimon** [comment]
@mdoron don't forget to fix the tests and unignore them before closing the issue.

**Comment by yuvalsimon** [comment]
@mdoron Checkout this case:
 ```
 private static Statement addAllBlocks(final IfStatement s, final List<Block> collectInto) {
    Statement $;
    $ = s;
    for (; iz.ifStatement($); $ = az.ifStatement($).getElseStatement()) {
      final Statement then;
      then = copy.of(then(az.ifStatement($)));
      Block b;
      b = az.block(then);
      if (b == null) {
        AST t1 = s.getAST();
        b = t1.newBlock();
        List<Statement> ss1 = step.statements(b);
        ss1.add(az.statement(then));
      }
      collectInto.add(b);
    }
    return $;
  }
```
goes to
 ```
 private static Statement addAllBlocks(final IfStatement s, final List<Block> collectInto) {
    Statement $;
    $ = s;
    for (; iz.ifStatement($); $ = az.ifStatement($).getElseStatement()) {
      final Statement then;
      Statement s1 = then(az.ifStatement($));
      then = copy.of(s1);
      Block b;
      b = az.block(then);
      if (b == null) {
        AST t1;
        t1 = s.getAST();
        b = t1.newBlock();
        List<Statement> ss1;
        ss1 = step.statements(b);
        Statement s1 = az.statement(then);
        ss1.add(s1);
      }
      collectInto.add(b);
    }
    return $;
  }
```
It makes error for _s1_. Probably the environment class does not include names in the nested if, and when athenizing a whole file it firstly expands the inner if and creates variable _s1_, and then it expands the containing scope. So you need to check also the namespace of the nested scopes when generating name.

**Comment by mdoron** [comment]
@yuvalsimon isn't there an override of `s1` in this case? Why is it a problem?

**Comment by yuvalsimon** [comment]
It might be hiding the outer `s1`, but I get error for this in eclipse. Read about hiding in java, it should sometimes work, but I believe it's alright to just assume that hiding is never allowed and generate different names.

**Comment by yossigil** [comment]
Yes. Yuval is right. You should never create hiding cases.

**Comment by mdoron** [comment]
@yuvalsimon @yossigil It's ok, I already created a function that searches for names in the children long time ago, we just need to put it in use.

**Comment by yuvalsimon** [comment]
Ok so for now should make another version of the function that does this, but for the release use the current implementation, that already works well when using wheel for zooming. The naming expanders are used only when using wheel for the current release.

**Comment by ravivos** [comment]
@dormaayan please assign this to your research as you said it is not part of our project

**Comment by OriRoth** [comment]
It IS a part of our project- we are generating names, for example in #1056 .
