### ISSUE TITLE
Bugs in StatementExtractParameters

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1104]
Few points:
1. We get duplicated imports.
2. Need to consider collisions when adding new imports, for example:
  if we have before using the expander only
  ```
  import org.eclipse.jdt.core.dom.Assignment.*;
  ```
  then if we add
  ```
  import org.eclipse.jdt.core.dom.InfixExpression.Operator;
  ```
  we cannot write `Operator.ASSIGN` because we get ambiguity. 
3. Some problem with lambda expressions:
  ```
  f3 = ¢ -> (¢.getName() + "").equals(az.simpleName(step.left(from)) + "");
  ```
  goes to
  ```
  boolean b1 = (¢.getName() + "").equals(az.simpleName(step.left(from)) + "");
  f3 = ¢ -> b1;
  ```
That's for now, maybe more problems but hard to tell before those are fixed.

**Comment by OriRoth** [comment]
1. You did not supplied an example code and I failed to recreate the problem.
2. This is a very complex issue, we'll deal with it someday but not now.
3. Done- no extraction from lambda expressions.

I have re-added the bloater to `InflateProvider`.

**Comment by yuvalsimon** [comment]
For 1 I meant we might get for example `import org.eclipse.jdt.core.dom.Assignment.*;` more than one time (appears more than one time in the code), just need to check if the import already exists before adding it.

**Comment by yuvalsimon** [comment]
@OriRoth When I run the athenizer on the project I get lots of errors of duplicate identifiers, for example:
 ```
 private static Statement addAllBlocks(final IfStatement s, final List<Block> collectInto) {
    Statement $;
    $ = s;
    for (; iz.ifStatement($); $ = az.ifStatement($).getElseStatement()) {
      final Statement then;
      then = copy.of(then(az.ifStatement($)));
      Block b;
      b = az.block(then);
      if (b == null) {
        AST t1 = s.getAST();
        b = t1.newBlock();
        List<Statement> ss1 = step.statements(b);
        ss1.add(az.statement(then));
      }
      collectInto.add(b);
    }
    return $;
  }
```
goes to
 ```
 private static Statement addAllBlocks(final IfStatement s, final List<Block> collectInto) {
    Statement $;
    $ = s;
    for (; iz.ifStatement($); $ = az.ifStatement($).getElseStatement()) {
      final Statement then;
      Statement s1 = then(az.ifStatement($));
      then = copy.of(s1);
      Block b;
      b = az.block(then);
      if (b == null) {
        AST t1;
        t1 = s.getAST();
        b = t1.newBlock();
        List<Statement> ss1;
        ss1 = step.statements(b);
        Statement s1 = az.statement(then);
        ss1.add(s1);
      }
      collectInto.add(b);
    }
    return $;
  }
```
However, it does not happen if we use the mouse wheel. 
Does the ctrl+alt+d runs the athenizer bottom up? If so this is a problem for the environment if we have to support athenizing whole project/file. Seems like the problem above is caused by running the athenizer bottom up.

**Comment by OriRoth** [comment]
Does it not Doron's issue then?

**Comment by yuvalsimon** [comment]
Yes it is but I worked on it too since we had to make it work already for this issue..
So I know what's going on there. It should not make this problem, but as I said, it happens only when athenizing whole project/file, but when you use the wheel it does not happen. Seems like it happens because of applying expanders bottom up, and if so it could be fixed only by changing to top down.

**Comment by OriRoth** [comment]
On hold, exemine after completing #1056

**Comment by OriRoth** [comment]
@yuvalsimon are those problems still valid? Where I can see them?

**Comment by yuvalsimon** [comment]
No, seems alright
