### ISSUE TITLE
Bug in StatementExtractParameters

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1155]
```
xs.forEach(λ -> addFragments(fragments(az.variableDeclarationExpression(λ))));
```
converted to
```
Consumer<?> c1 = λ -> addFragments(fragments(az.variableDeclarationExpression(λ)));
        xs.forEach(c1);
```
You can find this in MethodExplorer.java class.

**Comment by yuvalsimon** [comment]
Another bug:
```
$ = Stream.concat(¢.stream(), $);
```
goes to
```
Stream<@¢ @¢ E> es1 = ¢.stream();
        $ = Stream.concat(es1, $);
```
The code is from Recursive.java class

**Comment by OriRoth** [comment]
The second one is a problem with Eclipse I think... It duplicates annotation for template names for some reason (also in code auto-complete, for example).

**Comment by OriRoth** [comment]
On hold, examine after completing #1056

**Comment by OriRoth** [comment]
@yuvalsimon what's going on with this? I'll need proper details in order to check that seriously.

**Comment by yuvalsimon** [comment]
The second problem is solved, the first still exists. I wrote the details in the message already.

**Comment by OriRoth** [comment]
What file? I cannot work with this because of binding issue. Either specify class name or abstractize your example. It is a bit difficult, but necessary.

**Comment by yuvalsimon** [comment]
I wrote in the message already - `MethodExplorer.java`. It's in the spartanizer

**Comment by yuvalsimon** [comment]
@OriRoth I'll write only here from now on about new bugs in StatementExtractParameters. 
1. Many unresolved types, for example in guava project, class `SparseImmutableTable`:
```
@Override
  Cell<R, C, V> getCell(int index) {
    int rowIndex = cellRowIndices[index];
    Map.Entry<R, Map<C, V>> rowEntry = rowMap.entrySet().asList().get(rowIndex);
    ImmutableMap<C, V> row = (ImmutableMap<C, V>) rowEntry.getValue();
   ...
  }
```
goes to
```
@Override
  Cell<R, C, V> getCell(int index) {
    int rowIndex;
	rowIndex = cellRowIndices[index];
	Map.Entry<R, Map<C, V>> rowEntry;
	ImmutableList<Entry<R, Map<C, V>>> m1;
	ImmutableSet<Entry<R, Map<C, V>>> m3;
	m3 = rowMap.entrySet();
	m1 = m3.asList();
  ...
```
Entry cannot be resolved. 

2. In guave project, class AbstractMapBasedMultiset:
```
@Override
  Iterator<Entry<E>> entryIterator() {
    final Iterator<Map.Entry<E, Count>> backingEntries = backingMap.entrySet().iterator();
  ...
```
goes to
```
@Override
  Iterator<Entry<E>> entryIterator() {
    final Iterator<Map.Entry<E, Count>> backingEntries;
	Set<Entry<E, Count>> cs1;
	cs1 = backingMap.entrySet();
  ...
```
Results in incorrect number of arguments for type Entry (it should use Map.Entry but instead it uses Entry interface from the same package of this class)

**Comment by OriRoth** [comment]
OK should be fine. I basically rewrote a huge chunk of this class, so some other bugs may reappear... Closed for now.

**Comment by yuvalsimon** [comment]
@OriRoth there is duplicated annotations bug:
```
for (final Vertex<E> ¢ : unvisited) {
              stack.push(source(¢));
              break;
            }
```
goes to
```
for (final Vertex<E> ¢ : unvisited) {
              Vertex<@Nullable @Nullable E> e1 = source(¢);
              stack.push(e1);
              break;
            }
```
in spartan->AbstractGraph.java, it occurs many times

**Comment by OriRoth** [comment]
Eclipse's native *extract local variable* fails the same way for this case. I am allowing myself to ignore it. See e18472f5f237e4947bb2db08df24ce060dadd104.
