### ISSUE TITLE
Eliminate code clones in BloatTestUtils

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Main#1161]
Code was generated by copy and paste. Not good.

**Comment by dormaayan** [comment]
@yossigil : Are we going to change the tests for binding to what you showed me today now ? If yes I'll start to work on that right away and will change everything that is needed.

**Comment by dormaayan** [comment]
As far as I understand the bloater was changed so I don't think it is relevant now.

**Comment by OriRoth** [comment]
@NivShalmon you may reference this issue wherever you'll like.
