### ISSUE TITLE
Configuration option: Use 'it' instead of cent... 

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Main#1162]
Not urgent. But, eventually, this has to be done. 
@OriRoth  can help with the gui, but this is mostly internal work.

**Comment by OriRoth** [comment]
This would be included in @dormaayan 's planned tool. I will try to involve him more with GUI work so he would be able to do so by himself.

**Comment by yossigil** [comment]
The GUI/IT issue would be born in time,if you think the time is now do it

**Comment by dormaayan** [comment]
@OriRoth : thats can be a great introduction to the GUI world  for me, let's talk about that next week

**Comment by dormaayan** [comment]
In progress under issue #1222, a duplication

**Comment by dormaayan** [comment]
Done
