### ISSUE TITLE
A Python GitHub bot to remove email addresses

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Main#1184]
i.e., clean our code

**Comment by ravivos** [comment]
👍

**Comment by OriRoth** [comment]
Why GitHub bot? This should be changed in project's Eclipse preferences + simple Python script.

**Comment by yossigil** [comment]
Whatever....

**Comment by yossigil** [comment]
@ravivos , are you on this?

**Comment by ravivos** [comment]
I am

**Comment by yossigil** [comment]
News?

**Comment by ravivos** [comment]
We had more important issues and work to be done than this.
We are saving this one and the rest of the "on-hold" issues in our project for after the sprint 2 presentation at the end of week 10.
s.a #1326 , #1328, #1320, #1313, #950

**Comment by yossigil** [comment]
Never mind
