### ISSUE TITLE
Widget preferences page

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1224]
Open a new preferences page under `Spartanization tips`. Should include:
* Size of widget (numeric, 50-150 or something)
* Widget operations: checked list of maximum 8 (or so) widget operations (see class `WidgetOperation`), including image + description
* TBD

**Comment by OriRoth** [comment]
@ravivos you can get all available `WidgetOperation`s (also from other plugins' contributions!) via `WidgetOperationPoint.allOperations`, see #1291.

**Comment by ravivos** [comment]
<img width="677" alt="screenshot 2017-04-30 17 20 39" src="https://cloud.githubusercontent.com/assets/7875588/25565105/c661c58c-2dc9-11e7-8602-1a0b409b1127.png">
GUI of the preferences looks good, starting to work on the logic

**Comment by OriRoth** [comment]
1. No need for shortcut preference - there is an existing eclipse-core preferences for this ("Keys").
2. The widget list should contains *enabled, configured widgets only*, rather than all widgets. Then the buttons should be "add", "remove", "edit" etc.
3. Looks great.

**Comment by ravivos** [comment]
This is a big issue, therefore should be broken into two issues - #1315 , #1316

**Comment by OriRoth** [comment]
*Should not*. A lot of work != splitable.
