### ISSUE TITLE
GIT widget operations

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1226]
pull/commit+push/etc.
Relevant documentation:
* http://stackoverflow.com/questions/18139157/programmatically-find-the-repository-url-of-a-project
* https://maximilian-boehm.com/hp2118/Use-Java-Library-JGit-to-Programmatically-Access-Your-Git-Respository.htm

**Comment by OriRoth** [comment]
@dormaayan Stole your issue.

**Comment by OriRoth** [comment]
Did pull+push+commit (-am)

**Comment by ravivos** [comment]
Should display a message when getting an exception because not a git project.
@tomerdragucki maybe you would like this issue?

**Comment by OriRoth** [comment]
@tomerdragucki do it while you solve the jgit/egit issue.

**Comment by tomerdragucki** [comment]
See #1338
