### ISSUE TITLE
Deal with preferences versioning

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1268]
Backward and forward support.

**Comment by OriRoth** [comment]
Done for now. We'll have to deal with it again when we'll add more features.

**Comment by OriRoth** [comment]
I did not got backward compatibility, only forward. Waits for #1162.

**Comment by OriRoth** [comment]
@dormaayan do you want it for the next week? It's some XML work, might be fun (and teaching!).

**Comment by dormaayan** [comment]
@OriRoth Now in case we have an old xml file with relevant info about enabled/disabled tippers I use it while creating the new XML.
Done
