### ISSUE TITLE
returnDeadAssignment bug

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/Main#1281]
remove only if locally defined

**Comment by yossigil** [comment]
This is a result of a bug in the name space, Ithink.

**Comment by OriRoth** [comment]
Namespace should tell us what names are *defined* by the local scope, not only *known* by the scope... kind of.

**Comment by dormaayan** [comment]
Actually, there is an option to check if a variable was declared upwards, I chenged the checking for that and it seems ok now.

I close the issue

**Comment by yossigil** [comment]
:100:
