### ISSUE TITLE
Publish plugin launch configuration - convert to wiki

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1284]
See [here](http://eclipsesnippets.blogspot.co.il/2007/07/tip-creating-and-sharing-launch.html).

**Comment by OriRoth** [comment]
@yossigil I found a way to share Eclipse launch configurations via Eclipse (see first comment). After we'll make a wiki for it we would be able to integrate new requites more easily... (like Oran until recently).

**Comment by OriRoth** [comment]
It should be inserted to an existing wiki.
@ravivos ressign.

**Comment by tomerdragucki** [comment]
Now new developers can run as Eclipse Application by using an existing Launch Configuration file, located in the SpartanizerPlugin folder. more info in our wiki: Home->Developer Guide->Plugin debugging.
