### ISSUE TITLE
New Keyboard operations

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1287]
Add keyboard shortcuts for the zoom in and out

**Comment by OriRoth** [comment]
`ctrl++` / `ctrl+-`

**Comment by yuvalsimon** [comment]
`Ctrl+` / `Ctrl-` are occupied, so the shortcut will be `Ctrl[` / `Ctrl]` instead

**Comment by OriRoth** [comment]
NO. `Ctrl+wheel` was also occupied, but I hacked it. You should do something similar. First learn thoroughly how `InflateListener` works, then add your additions.

**Comment by OriRoth** [comment]
I checked, and the existing `ctrl+`/`ctrl-` are not that crucial. Anyway, we override it only when zoom is in action, so it is only temporary.

**Comment by yuvalsimon** [comment]
They scale up/down the text, I personally use it a lot. Not us all have good eyes :)

**Comment by OriRoth** [comment]
Not on my machine... anyway, you may generalize your implementation to any key combination, then Yossi would decide what he wants.

**Comment by yuvalsimon** [comment]
@OriRoth didn't you mean to add shortcuts that don't have to be activated via ctrl+alt+d? (like current ctrl+5 shortcut)

**Comment by OriRoth** [comment]
No. Unless the client requires it.

**Comment by yuvalsimon** [comment]
@ravivos could you ask the client please? (whether he wants the bloat/spartan shortcuts to be activated always or should be able to turn on/off with ctrl+alt+d)

**Comment by OriRoth** [comment]
@yuvalsimon this issue is quite *urgent*, please do *not* wait for an answer. If it will be written properly, converting it to either configuration should be simple.

**Comment by ravivos** [comment]
As @OriRoth said, It doesn't matter, just finish this issue as if the shortcuts should be ctrl+/ctrl- **when the plugin is turned on** and if Yossi asks for different keyboard shortcuts, we will change it.
Anyways, I have asked Yossi and am waiting for an answer but this is irrelevant for you, just do the ctrl+/ctrl-

**Comment by yuvalsimon** [comment]
The shortcut is `ctrl + alt + +/-`, and the plugin have to be turned on before (with `ctrl + alt + d`)

**Comment by yossigil** [comment]
Client request: shortcut should be **always** available.

**Comment by OriRoth** [comment]
Done! You can set whether you want the zoomer to be activated on startup (enabled by default).

![good](https://cloud.githubusercontent.com/assets/15183108/26282023/c4f47c6a-3e10-11e7-8752-1ff0d01c5a05.jpg)

**Comment by ravivos** [comment]
@OriRoth, the shortcuts (zoomer and spartanizer) are not enabled on default... at least not in my computer (MAC - UNIX).
I have to press cntrl+alt+d and then I can use the shortcuts and the scroller
