### ISSUE TITLE
expand WidgetContext

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/Main#1292]
Currently, widget context only gives a very basic information, and more information should be added based on need. Things like current project, current file and current selection should all be stored here. Related to #1225 since the widget buttons will set this object up for the operation

@OriRoth  @dormaayan @ravivos @tomerdragucki @yuvalsimon if you need anything to be added to this while working on a widget operation, let me know here.

**Comment by OriRoth** [comment]
Great job Niv!

**Comment by yuvalsimon** [comment]
Niv can you add to context the location of the button on the screen please?

**Comment by OriRoth** [comment]
@yuvalsimon it is not required for your widget operation #1227. Why do you need it?

**Comment by tomerdragucki** [comment]
Can you add 
```
public Selection currentSelecetion;
public Selection currentCompilationUnit;
public Selection allCompilationUnits;
```
to the context? you might wanna look at TopMenuHandler class.

**Comment by OriRoth** [comment]
@NivShalmon It can be done using `Selection.Util.?`, see `TopMenuHandlers`

**Comment by NivShalmon** [comment]
@tomerdragucki next time, please wait for me to add the fields, since I need to see whether I can do that or not. It's fine this time since these field were intened and only missing since no one bothered adding them. Also, sorry for the long delay, but I couldn't get any work in for the last few days due to #1310, the holidays and @OriRoth's work.

@yuvalsimon see how @tomerdragucki asked for fields to be added? That's how you should format this. Also, do you still need this field?

**Comment by yuvalsimon** [comment]
I don't need them, I used mouse location instead. Thanks anyway

**Comment by OriRoth** [comment]
Mouse location is a part of the current context...

**Comment by NivShalmon** [comment]
@SpartanRefactoring/zoomers @yuvalsimon anything else that you think should be added here before the release?

**Comment by OriRoth** [comment]
Everyone should know how to use `WidgetContext` by themselves by now. @NivShalmon close this please (and add to your weekly TODOs).
