### ISSUE TITLE
Preferences GUI review

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1296]
- [x] Use `TipperCategory`s, not `TipperGroup` (**delete** `TipperGroup` class)
- [x] Add category description to GUI

**Comment by OriRoth** [comment]
@yossigil Done! Changes to tippers selection window:
* Added categories descriptions
* Categories are `TipperCategory` instead of `TipperGroup`
* Categories are ordered in a tree (bonus!)

I have not removed/deprecated `TipperGroup` because it is being used in many places... (should be considered deprecated).

![cool](https://cloud.githubusercontent.com/assets/15183108/25760250/9fe5a50e-31de-11e7-951f-7af216aea9c0.jpg)

**Comment by OriRoth** [comment]
BTW, not all categories have valid description. Tell me if you want me to remove their tooltips/fix description.

**Comment by yossigil** [comment]
:100: I would try to work on the descriptions
