### ISSUE TITLE
Circular dependency in JGit

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1305]
JGit, required for git widget operations, has a known circular dependency issue (that prevents plugin export). If it cannot be solved, the git widget operations should be removed.
Relevant material:
* http://stackoverflow.com/questions/13589048/osgi-logback-slf4j-eclipse-run-configuration

![blocker](https://cloud.githubusercontent.com/assets/15183108/25541355/049b8a6e-2c57-11e7-8fa6-83999a88bc12.jpg)

**Comment by OriRoth** [comment]
@ravivos we can try working with `egit` instead of `jgit`. I could not found a documentation, so it might be a little tricky. You can reassign if someone else want to work on this.
https://github.com/eclipse/egit

**Comment by ravivos** [comment]
I think @tomerdragucki  would like another Issue due to lack of some and this one looks interesting

**Comment by tomerdragucki** [comment]
Plugin export succeed when building via update site project in Eclipse.
