### ISSUE TITLE
Connect the JoyStick to the Plugin

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Main#1306]
Connect the JoyStick to the plugin and operate it as the mouse roller:

- Up: Bloating the code
- Down: Spartanization of the code

**Comment by OriRoth** [comment]
What's going on? Is it my turn to play with it already?

**Comment by dormaayan** [comment]
No,@OriRoth We are going to play together next week (:
I'll look for more information until our weekly meeting but obviously that issue will go on to week 7 as well

**Comment by dormaayan** [comment]
@OriRoth : I think that the main goal of that issue for the last week was achieved, I close that issue, we will display the results in our meeting and decide together how to go on with that

**Comment by yossigil** [comment]
:100:
