### ISSUE TITLE
Table_* throws java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by M4tt30rru** [SpartanRefactoring/Main#1308]
Same as in #1307 for 

- Table_RawNanoStatistics
- Table_Prevalence
- Table_Constants
- Table_Iteratives
- Table_Effectiveness
- Table_NanosDistribution

**Comment by yossigil** [comment]
Can you solve this?

**Comment by M4tt30rru** [comment]
Already solved. Closing the issue.
