### ISSUE TITLE
Plugin.loadPrefrences throws exceptions

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/Main#1310]
loadPrefrences throws exceptions without handeling them, which cuases the plugin to fail:
1. line 139 throws arrayOutOfBounds exception when the workspace is empty
2. line 140 thorws nullPointerException sometimes, Don't know why in this case.
@OriRoth "fixed" this with a try/catch block for now, but this needs to be fixed properly

**Comment by OriRoth** [comment]
Be sure to check 6cce082 as well.

**Comment by OriRoth** [comment]
@dormaayan you have added more code after this issue has been written (not opened), so be sure to check it as well.

**Comment by OriRoth** [comment]
Also `PreferencePage`- should be null risk free! (as much as possible)

**Comment by dormaayan** [comment]
@OriRoth : I'm currently work on that, In case of exception I will delete the XML and create it again one more time

**Comment by dormaayan** [comment]
Done
