### ISSUE TITLE
Robust.ly run Plugin.start

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1311]
@dormaayan set milestone. Easy-peasy, while dealing with #1310.

**Comment by dormaayan** [comment]
Got it

**Comment by OriRoth** [comment]
Implement in *Plugin.java*.

**Comment by dormaayan** [comment]
Done

**Comment by OriRoth** [comment]
Spartanizer on student's day?!

**Comment by dormaayan** [comment]
Stocking over my commits and reading emails on student's day O:
Shame on you Mr. Roth...
