### ISSUE TITLE
example test failing LocalInitializedNewAddAll

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1314]
commented out the example and opened an issue with the author as an Assignee, just as our Coding standard say

**Comment by OriRoth** [comment]
There is no comment-out policy in our coding standards.

**Comment by ravivos** [comment]
@OriRoth - there is an ignoring+opening an issue policy for tests which is equivalent to commenting-out+TODO+opening an issue policy for exampleTests

**Comment by yossigil** [comment]
@NivShalmon : you may wish to fix this bug, and en route, implement  a corresponding bloater

**Comment by NivShalmon** [comment]
Tipper now works, opened #1421 for the corrosponding bloater
