### ISSUE TITLE
Notation/spartanizer.xml UTF-8

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1317]
You put something else then `¢` there- then the xml file is not parsable.
![bad](https://cloud.githubusercontent.com/assets/15183108/25659191/59eb23e2-300f-11e7-85ee-fdc7eaf43310.jpg)

**Comment by dormaayan** [comment]
@OriRoth : No, I initialize it with ¢, and then put normal strings there

**Comment by OriRoth** [comment]
There *is* a problem. Be sure not to put there UTF-8 stuff (or solve in other way).

**Comment by dormaayan** [comment]
Solved that, I'm not using ¢ in the XML file

**Comment by OriRoth** [comment]
Great job Dor 🎉
