### ISSUE TITLE
Use the widget operations the user configured

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/Main#1321]
The widget handler already choses the widgetOperations from an array, so once #1316 is finished we will simply need to create this array properly.

**Comment by OriRoth** [comment]
Operations configuration should be saved in preference store- simple to put in, simple to put out. @ravivos will put the user preferences in the store, then @NivShalmon will create blank tippers and initialize them using `register` by the configuration. @NivShalmon wait for @ravivos to finish this so you'll use actual constantas.

**Comment by ravivos** [comment]
finished my part @NivShalmon

**Comment by NivShalmon** [comment]
@ravivos already did his part, but since I was on vacation on week 7 this is moved to week 8

**Comment by NivShalmon** [comment]
@ravivos 
Things we need to do this week to finish this issue:

- create an entry class containing an operations serialUID, the configuration of the widget and a boolean isEnabled.
- make serialization work
- replace current configuration storing with a list of entries.
- create the default list of enteries in WidgetPrefernces.setDefaults
- update WidgetPrefernces to use the decided protocol, a list of enteries
- load entries according to the list. Up to seven entries will have isEnabled on, and they are the active operations. Their order in the list is also their order on display/on the widget.
- change getWidgetOperations to read operations from the store
- organize the code until it is maintainable

**Comment by yuvalsimon** [comment]
@NivShalmon note that in WidgetPreferences line 98 (`final ByteArrayInputStream $ = new ByteArrayInputStream(Base64.getDecoder().decode(store().getString(OPERATIONS_ORDER).getBytes()));`) there is IllegalArgumentException when starting eclipse. Fix it before closing the issue...
