### ISSUE TITLE
Test run not clean

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1323]
I have checked and test runs in research fail.
Only since we moved to the new packaging method

**Comment by OriRoth** [comment]
Next time open an existing issue... I think we have world-record in issues count.

**Comment by OriRoth** [comment]
Why am I assigned? Only because the test fail does not mean it is my fault... You should've checked first.

**Comment by yossigil** [comment]
@AdiOmari : FYI.

**Comment by tomerdragucki** [comment]
Should I ignore the tests and add TODO for the tests author?

**Comment by tomerdragucki** [comment]
Test run is clean. Ignored failing tests, added TODOs and opened issues.
