### ISSUE TITLE
Widget doesn't show on clicking the toolbar shortcut in MacOS

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1324]
Apple fanboys, do you also have this bug?
@tomerdragucki , @dormaayan

**Comment by OriRoth** [comment]
Check errors are not thrown in the console.

**Comment by dormaayan** [comment]
@OriRoth : Everything seems ok with the toolbar shortcut, the only problems occur while pressing the buttons on the widget, but that's of course from known reasons
