### ISSUE TITLE
OutlineTernaryMethodInvocation tip returns null

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1334]
This is a design bug! `tip` method should not return null!
I causes many troubles. For example, athenization of this code is stuck because your tipper sends a tip that fails:
```Java
public class B {
  int d(int x) {
    return 1;
  }

  int s(int x) {
    switch (d(x)) {
    case 1:
      return 1;
    case 2:
      return 2;
    default:
      return 3;
    }
  }

  void f() {
    String s;
    s = C.a().toString();
  }
}
```

**Comment by OriRoth** [comment]
This is a mini-blocker, because it hurt debugging. Maybe just first priority... easy fix, after all.

**Comment by yuvalsimon** [comment]
Not mine (it was rewritten using patterns), I'll fix it anyway

**Comment by OriRoth** [comment]
You are the author. If this is a mistake, rewrite it and reassign.
