### ISSUE TITLE
research on 1/3,2/3 trees

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1336]
maybe add a wiki and also explain how it can be added to our project and help us

**Comment by ravivos** [comment]
@dormaayan 
I think it might be interesting to work on this together, what do you think?

**Comment by yossigil** [comment]
No need to research, it is trivial.

**Comment by OriRoth** [comment]
Clues: check `StatementExtractParameters::choose` and `OperationsProvider::getFunction`.
