### ISSUE TITLE
review for each tipper - matching zoomer if such exists

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1337]
for each tipper - match the zoomer if such exists, else - open a "new-zoomer" issue.
Also, add pointers from each tipper to expander and vice versa (or a better implmentation because I personally don't support bi-pointers but Yossi did have a point when he suggested it, so maybe consult him).

**Comment by OriRoth** [comment]
@ravivos you can make a mapping-table in this issue.

**Comment by tomerdragucki** [comment]
| Tipper  | Expander |
| ------------- | ------------- |
|   |   |
|   |   |

**Comment by yuvalsimon** [comment]
https://github.com/SpartanRefactoring/Main/commit/d8b1d187c4b3484930d8fd4c70d61376fb5a276c
It's alright?
