### ISSUE TITLE
Add UI to git operations

### ISSUE THREAD

**Issue by tomerdragucki** [SpartanRefactoring/Main#1338]
So the user will get indication when an operation is done.
#1226

**Comment by yuvalsimon** [comment]
I think should print the output to the console (and also if there is git conflict the user might have to give input if the git api asks for ,or just fail it)

**Comment by OriRoth** [comment]
Maybe.. though *egit* just pop a window for the user, so....
Also, I do not know how to write to **a** console (do you?).

**Comment by yuvalsimon** [comment]
I meant to just print the output to eclipse console with system.out.println...

**Comment by OriRoth** [comment]
Use `note` for it, though I do not see why you would need it...

**Comment by ravivos** [comment]
@yuvalsimon this is not a good use-case because the client is not aware of the prints nor the notes when he uses the plugin.
There should be a dialog popping or something built in from egit for example as Ori said

**Comment by yossigil** [comment]
:+1
