### ISSUE TITLE
Exception in MultiplicationToCast

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1340]
In guava project in class _Murmur3_128HashFunction_ it throws _NumberFormatException_ on `k * 0xff51afd7ed558ccdL`

**Comment by dormaayan** [comment]
@yuvalsimon : please clarify yourself, the way you described doesn't help me in any way.
Isolate the concrete example from there and put it here so I will solve it

**Comment by yuvalsimon** [comment]
I wrote the example in the first message.... (**`k * 0xff51afd7ed558ccd`**) Just run on it and you'll see exception. 
Adding test case

**Comment by yuvalsimon** [comment]
Still throws exception..

**Comment by dormaayan** [comment]
Test pass I close

**Comment by OriRoth** [comment]
@dormaayan you should also verify the console is clean of errors while running.

**Comment by dormaayan** [comment]
Now really done...
