### ISSUE TITLE
Study on AssertJ

### ISSUE THREAD

**Issue by orenafek** [SpartanRefactoring/Main#1341]
Figure out what are the fundamental method calls and common use case.

**Comment by OriRoth** [comment]
You may look up "Assertions Generator". It is in the [top menu](http://joel-costigliola.github.io/assertj/), so they must be considering it one of their main features. In short, this is assertion fluent API source generator that uses external [templates](https://github.com/joel-costigliola/assertj-assertions-generator/tree/master/src/main/resources/templates).

**Comment by orenafek** [comment]
@OriRoth 
Thanks for the help, but I believe there is a more relevant part of AssertJ to my research.

**Comment by orenafek** [comment]
AssertJ have developed a shell script that translates a JUnit code to a fluent API. this can be found [here](https://github.com/joel-costigliola/assertj-core/blob/master/src/main/scripts/convert-junit-assertions-to-assertj.sh).
My mission will be to take this shell script and turn it into distinct tips 🙌 .

**Comment by yossigil** [comment]
Interesting, let's talk on this on our Monday meeting

**Comment by orenafek** [comment]
For now, I've decided to implement these transformations in code. 
In case they will be handy.
** THIS IS PUSHED TO branch: gradle_build_fix **

**Comment by yossigil** [comment]
Can you merge into main branch?

**Comment by OriRoth** [comment]
It is currently included in `gradle_semi_integration` branch that will be merged into `mazter` soon @RoeiRaz .
@orenafek it is your responsibility to check this merge has been done correctly (It should be fine...).

**Comment by orenafek** [comment]
I have these files locally for backup. 
I've been working with IntelliJ since `gradle_build_fix` has been ready.
But I'll add these into `mazter` using eclipse.

**Comment by yossigil** [comment]
Keep this issue hot

**Comment by orenafek** [comment]
Change were pushed to `mazter`
