### ISSUE TITLE
Slow zommer

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1343]
The zoomer is slow AF (zomming whole project) (it is like, 1 file per second).
@yuvalsimon I suspect it is because `StatementExtractParameters`- it became a binding monstrosity.
@ravivos check whether we can ignore this- never I have understood why we need a "zoom whole project" option.

**Comment by yuvalsimon** [comment]
Yes it's very very slow. The client should decide whether he wants that feature... 
Yet we need it for finding bugs

**Comment by ravivos** [comment]
Checking it out with our client

**Comment by ravivos** [comment]
decided to remove a feature and add a test case to test it instead - #1345
