### ISSUE TITLE
DisableSpartanization on RawSpartanizer

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Main#1353]

**Comment by OriRoth** [comment]
Solved: the Java parser did not parsed JavaDoc comments. *[source](https://www.eclipse.org/forums/index.php/t/378764/)*

**Comment by OriRoth** [comment]
[Wiki](https://github.com/SpartanRefactoring/Main/wiki/Tutorial) updated.

**Comment by yossigil** [comment]
Thanks
