### ISSUE TITLE
Make gradle build RawTokenizer

### ISSUE THREAD

**Issue by RoeiRaz** [SpartanRefactoring/Main#1355]

**Comment by yossigil** [comment]
What's up?

**Comment by RoeiRaz** [comment]
Sorry for the long wait 😞 
i added a gradle task that runs jflex jar on the relevant file, and it seems to be working fine (but it will require maintenance if the flex file will be renamed). It is executed automatically when 'il.org.spartan.spartan' is built using gradle.

**Comment by yossigil** [comment]
:+1:
