### ISSUE TITLE
Bugs in BooleanExpressionBloater

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1356]
```
return λ -> c1.holds(λ) || c2.holds(λ);
```
goes to
```
boolean b5;
      b5 = c1.holds(λ);
      boolean b6;
      b6 = c2.holds(λ);
      return λ -> b5 || b6;
```
and also
```
int cpIndex = i.args()[1] | i.args()[0] << 8;
```
goes to
```
int cpIndex;
boolean b5;
      b5 = i.args()[1];
      boolean b6;
      b6 = i.args()[0] << 8;
      cpIndex = b5 | b6;
```
Run the athenizer on the project to check that no errors appear

**Comment by ravivos** [comment]
#980 
instead of opening a new issue, I think we should open the original one, shouldn't we?

**Comment by yossigil** [comment]
"instead of opening a new issue, I think we should open the original one, shouldn't we?"

Yes

@SpartanRefactoring/zoomers
