### ISSUE TITLE
Unused parameter to underscore

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1364]
<a href="https://github.com/amirsagiv83"><img src="https://avatars2.githubusercontent.com/u/15860047?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [amirsagiv83](https://github.com/amirsagiv83)**
_Monday Mar 20, 2017 at 16:48 GMT_
_Originally opened as https://github.com/TechnionYP5777/Leonidas-FTW/issues/112_

----

the tip will be able to spot an unused parameter in a method and change it to "_".

**Comment by AnnaBel7** [comment]
In order to finish this tipper, we will need a basic block that represents "any number of parameters" in the method declaration.

**Comment by OriRoth** [comment]
Consider double underscore, i.e. `__` . A single underscore is reserved by
some compilers, so you may get a warning for it.

**Comment by OriRoth** [comment]
Also `_1` `_2` etc. for multiple unused parameters.
