### ISSUE TITLE
Weekly log for Roei Raz

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1372]
<a href="https://github.com/RoeiRaz"><img src="https://avatars2.githubusercontent.com/u/7161024?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [RoeiRaz](https://github.com/RoeiRaz)**
_Saturday Mar 25, 2017 at 09:40 GMT_
_Originally opened as https://github.com/TechnionYP5777/Leonidas-FTW/issues/127_

----

**Comment by RoeiRaz** [comment]
## Week 1-2
Wrote a custom logging tool, and some tests for it
https://github.com/SpartanRefactoring/Main/issues/1366

## Week 3-4
Bug fixes,
worked with @OriRoth on migrating the Spartanizer to gradle.

## Week 5-8
Transferred Leonidas repo, with all the commit history, to the Spartanizer repo.
Wired the gradle model to make Leonidas be dependent on the Spartanizer (like requested), so we'll be able to use classes from the Spartanizer.
(These gradle issues took long time 😞 )

## Week 9
Vacation

## Week 10
GUI tinkering. added Icons, and integrated and syntax highlighting library into our project, to be used in the Toolbox GUI. Made the highlighting color scheme match the current IntelliJ scheme.

## Week 11
Vacation

# Week 12
Added an option to spartanize the entire project, worked with @amirsagiv83 on 'edit tipper' option.

# Week 13
Debugged the project, tried installing it from scratch to see if there are any issues left. Fixed jacoco issues, and participated in efforts to reach 70% line coverage in the tests.
