### ISSUE TITLE
 Allow batch spartanization from intelij

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1377]
<a href="https://github.com/yossigil"><img src="https://avatars2.githubusercontent.com/u/12775400?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yossigil](https://github.com/yossigil)**
_Monday Apr 03, 2017 at 10:16 GMT_
_Originally opened as https://github.com/TechnionYP5777/Leonidas-FTW/issues/158_

----

None

**Comment by RoeyMaor** [comment]
Is this issue still relevant? we know how to import our project to eclipse

**Comment by michalcohen** [comment]
What is the state of this issue? What is this "batch spartanization"? @RoeyMaor  @RoeiRaz

**Comment by michalcohen** [comment]
?

**Comment by amirsagiv83** [comment]
@RoeiRaz  can we close this??

**Comment by michalcohen** [comment]
? @RoeiRaz
