### ISSUE TITLE
Tests for LeonidasTipper

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1380]
<a href="https://github.com/michalcohen"><img src="https://avatars1.githubusercontent.com/u/11704810?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [michalcohen](https://github.com/michalcohen)**
_Saturday Apr 29, 2017 at 12:55 GMT_
_Originally opened as https://github.com/TechnionYP5777/Leonidas-FTW/issues/192_

----

**Comment by RoeyMaor** [comment]
<a href="https://github.com/michalcohen"><img src="https://avatars1.githubusercontent.com/u/11704810?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [michalcohen](https://github.com/michalcohen)**
_Saturday May 13, 2017 at 10:22 GMT_

----

Are the commented tests the old ones?

**Comment by michalcohen** [comment]
@orenafek  I see the tests are commented. Can we take them out of the comment, or are there any more modifications you wish to do to these tests?

**Comment by orenafek** [comment]
@michalcohen 
for now they can be undocumented

**Comment by michalcohen** [comment]
@orenafek 
Apparently I can't uncomment them because they won't compile.

**Comment by michalcohen** [comment]
So is it something you believe can be done? @orenafek

**Comment by orenafek** [comment]
I'm pretty sure it's possible, but requires some technological overcomings
