### ISSUE TITLE
Create a general testing mechcanism for all tippers

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1381]
<a href="https://github.com/RoeyMaor"><img src="https://avatars2.githubusercontent.com/u/16507852?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [RoeyMaor](https://github.com/RoeyMaor)**
_Saturday Apr 29, 2017 at 16:49 GMT_
_Originally opened as https://github.com/TechnionYP5777/Leonidas-FTW/issues/194_

----

Create a general testing mechanism for all tippers that will operate by examples given by the tipper classes themselves.

**Comment by RoeyMaor** [comment]
<a href="https://github.com/michalcohen"><img src="https://avatars1.githubusercontent.com/u/11704810?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [michalcohen](https://github.com/michalcohen)**
_Friday May 12, 2017 at 05:09 GMT_

----

Is there any progress?

**Comment by RoeyMaor** [comment]
<a href="https://github.com/RoeyMaor"><img src="https://avatars2.githubusercontent.com/u/16507852?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [RoeyMaor](https://github.com/RoeyMaor)**
_Saturday May 20, 2017 at 14:41 GMT_

----

will update

**Comment by michalcohen** [comment]
Is the solution you've talked with Anna about worked here? Can we close this issue?
@RoeyMaor

**Comment by RoeyMaor** [comment]
no, this should be moved to the next milestone

**Comment by RoeyMaor** [comment]
depends on #1478

**Comment by RoeyMaor** [comment]
![screenshot from 2017-06-17 17-22-15](https://user-images.githubusercontent.com/16507852/27253734-9fb8ce4c-5382-11e7-97dd-25bf9302af6d.png)

tests now work on both leonidas and non-leonidas tippers. i have included two example auto-tests, one for safereference (that passes), and one for MethodInvocationToStringToEmptyStringAdditionTest which doesnt pass. to see the reason a test didnt pass one must enable the prints for that test, and that is done by passing true to the TipperTest constructor for the parameter "prints"
