### ISSUE TITLE
Implemting building block arithmetic

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1382]
<a href="https://github.com/michalcohen"><img src="https://avatars1.githubusercontent.com/u/11704810?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [michalcohen](https://github.com/michalcohen)**
_Sunday Apr 30, 2017 at 12:04 GMT_
_Originally opened as https://github.com/TechnionYP5777/Leonidas-FTW/issues/197_

----

For example 4 + 5 - 4

**Comment by SharonKL** [comment]
Instead of a building block, this has been added as a possible constraint for the Expression basic block.
