### ISSUE TITLE
Implement Class basic block

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1387]
<a href="https://github.com/michalcohen"><img src="https://avatars1.githubusercontent.com/u/11704810?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [michalcohen](https://github.com/michalcohen)**
_Sunday May 14, 2017 at 14:00 GMT_
_Originally opened as https://github.com/TechnionYP5777/Leonidas-FTW/issues/220_

----

**Comment by amirsagiv83** [comment]
@michalcohen  can we close this?

**Comment by michalcohen** [comment]
@amirsagiv83 
Unfortunately no, we didn't solve yet the problem when there are more elements in the matched class than in the matcher. The way I see the solution is to try to match each matcher template method, for example, with a method of the user. and once we know for each template method, what are its options - to try every option that sets each template method a single unique user method (the same for fields and inner classes).

**Comment by michalcohen** [comment]
@amirsagiv83 
I uploaded an attempt of solving this issue, and tried it on multiple instances. Can you try it on some instances of your own (maybe via #1436 ) in order to test the behaviour of this basic block?

**Comment by amirsagiv83** [comment]
On it!
