### ISSUE TITLE
Merging ToolBox controller with EditTipper

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1389]
<a href="https://github.com/amirsagiv83"><img src="https://avatars2.githubusercontent.com/u/15860047?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [amirsagiv83](https://github.com/amirsagiv83)**
_Friday May 19, 2017 at 10:12 GMT_
_Originally opened as https://github.com/TechnionYP5777/Leonidas-FTW/issues/226_

----

the two UI are supposed to be connected.

**Comment by amirsagiv83** [comment]
@AnnaBel7  can I close this?

**Comment by AnnaBel7** [comment]
yes, it's done.
