### ISSUE TITLE
Saving Toolbox controller information for future runs. 

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1390]
<a href="https://github.com/amirsagiv83"><img src="https://avatars2.githubusercontent.com/u/15860047?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [amirsagiv83](https://github.com/amirsagiv83)**
_Friday May 19, 2017 at 10:13 GMT_
_Originally opened as https://github.com/TechnionYP5777/Leonidas-FTW/issues/227_

----

ToolBox controller must save the information for one run to the next one.

**Comment by AnnaBel7** [comment]
Information about the subject can be found [here](http://www.jetbrains.org/intellij/sdk/docs/basics/persisting_state_of_components.html) and [here](http://corochann.com/intellij-plugin-development-introduction-persiststatecomponent-903.html).

**Comment by OriRoth** [comment]
Maybe try implementing [Configurable interface](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-api/src/com/intellij/openapi/options/Configurable.java) suggested in [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206147439-Can-I-open-my-plugin-settings-programmatically-).

@amirsagiv83

**Comment by OriRoth** [comment]
Also here is a [complete guide](http://corochann.com/intellij-plugin-development-introduction-applicationconfigurable-projectconfigurable-873.html) (looks nice).

**Comment by amirsagiv83** [comment]
For now i solved the problem. next spring we will need to upgrade the way we save the information
