### ISSUE TITLE
Transport all issues to new repository

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1391]
<a href="https://github.com/RoeyMaor"><img src="https://avatars2.githubusercontent.com/u/16507852?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [RoeyMaor](https://github.com/RoeyMaor)**
_Sunday May 21, 2017 at 07:06 GMT_
_Originally opened as https://github.com/TechnionYP5777/Leonidas-FTW/issues/229_

----

**Comment by RoeyMaor** [comment]
I used a script to migrate the issues, but due to problems with conflicting labels, i had to remove some labels from the issues, and i will manually add them back. also, i will manually add back the assignees

**Comment by RoeyMaor** [comment]
The message above only affects the Intellij issues

**Comment by OriRoth** [comment]
*new-tipper* label and such should be labeled with *IntelliJ* as well, to avoid confusion (or renaming of both *new-tipper* labels?).

**Comment by RoeyMaor** [comment]
@OriRoth Will there be confusion even if the issue is labled with IntelliJ?

**Comment by yossigil** [comment]
I am not sure I approve
