### ISSUE TITLE
Long project loading time when importing p2 dependencies

### ISSUE THREAD

**Issue by RoeiRaz** [SpartanRefactoring/Main#1393]
In order to compile the spartanizer plugin using gradle, i had to include p2 dependencies somehow. to do this, i used a gradle plugin that downloads p2 dependencies from a specified repository and installs them locally in the build directory as a 'maven repository' from which gradle can use them (the project 'target.p2' uses that plugin).
The main problem with that is that **the downloading time of these p2 dependencies is very long**, it can take almost half an hour or even more with slower internet connections, **but it should only be a one time event**. 
for that reason, i still haven't made 'target.p2' a subproject (in order to not make everyone experience these loading times), but i didn't find a better solution, so i think its necessary.
@yossigil do i have a green light? 😄 

**UPDATE 22/05**: After a discussion with yossigil we decided that the loading time is acceptable. make sure you don't clean the project target.p2, because the dependencies are saved in its build directory (if you accidentally delete this directory, you'll have to wait for the dependencies to be downloaded again).

**Comment by yossigil** [comment]
Call me voice

**Comment by yossigil** [comment]
We have to live with it!
