### ISSUE TITLE
Bug in MethodInvocationTernaryBloater

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1395]
In class GUITraversal the method
```
public void setSelection(final AbstractSelection<?> ¢) {
    setSelection(¢ == null || ¢.textSelection == null ? null : ¢.textSelection);
  }
```
goes to
```
  public void setSelection(final AbstractSelection<?> ¢) {
    if ((¢ == null) || (¢.textSelection == null)) {
      setSelection(null);
    } else {
      setSelection(¢.textSelection);
    }
  }
```
results in ambiguity error for setSelection(null) (since setSelection is overloaded)

**Comment by NivShalmon** [comment]
you can use type.of to tell whether something is null or not

**Comment by tomerdragucki** [comment]
Adding cast appeared to be very complicated (adding imports etc like in @OriRoth 's StatementExtractParameters bloater) so currently just disabled the bloater on the problematic occasions.

**Comment by yuvalsimon** [comment]
@tomerdragucki you can for now enable the bloater, just restrict it not to tip when there is null. Keep the issue open if you think we should enhance it later to adding castings.

**Comment by OriRoth** [comment]
Remove on hold- implement Yuval's simple solution, it is sufficient.

**Comment by OriRoth** [comment]
Why is it on hold?

**Comment by tomerdragucki** [comment]
I already implemented and pushed the simple solution. The second implementation is on-hold
