### ISSUE TITLE
Longer\Shorter Names With Joystick

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Main#1399]
Use Joystick gestures to make names shorter\longer

**Comment by yossigil** [comment]
:+1:

**Comment by yuvalsimon** [comment]
I get tons of exceptions, don't add it until it works please @dormaayan

**Comment by OriRoth** [comment]
It should not be a part of the Toolbox, so....

**Comment by dormaayan** [comment]
Done

**Comment by yuvalsimon** [comment]
@dormaayan the tests stuck!! please don't commit before running ALL tests

**Comment by dormaayan** [comment]
@yuvalsimon : Sorry I also committed something else that is not related, I fix now

**Comment by dormaayan** [comment]
@yuvalsimon : Now it's ok

**Comment by yuvalsimon** [comment]
Cool, thanks!

**Comment by OriRoth** [comment]
@dormaayan we need a zooming-like keyboard shortcut for the joystick.
