### ISSUE TITLE
bug when removing an operation from WidgetPreferences

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1403]
when removing an operation, it doesn't apply the removal but cuts the dependency.
I suspect this is happening because the list in the ListEditorOperation is actually an array of strings that don't change - SHOULD CHECK THIS ASAP

**Comment by tomerdragucki** [comment]
That maybe too late for this sprint but I think it would be clearer if when I enable "Git commit" operation (for example), it disappears from "Configure operations for list:" (the upper one) and appears in the list below ("enabled operations"). Than, when I want to disable an operation, I'll press on it on the second list and disable, and it'll move back to the upper list.

**Comment by tomerdragucki** [comment]
Should there be an option to add to the "Configure operations for widget" an operation that already appears there (I think we shouldn't allow that)? because currently it let's me do it and then the operation doesn't work properly- pressing on enable operation for it does nothing.

**Comment by ravivos** [comment]
moved to week 10 - won't be ready for the closest release

**Comment by ravivos** [comment]
will be automatically done when #1402 is done
