### ISSUE TITLE
endless loop of exceptions when running plugin on a runtime project with spartan.xml

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1404]
Use case:
- open the plugin in run mode
- open the spartanizer project in eclipse application workspace for debugging it
- close the plugin
- run the plugin again

**Comment by yuvalsimon** [comment]
Does it still occur @ravivos ?
I don't understand the description...

**Comment by yuvalsimon** [comment]
Open the issue if it still occurs
