### ISSUE TITLE
Review the "user manual" wiki

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1407]
For the presentation.
Review that the user manual is understandable for every possible user (user manual for dummies) and contains examples.
Should target a client and a contributor - so we need two parts in this wiki.
Should be checked on every OS (linux,windows,os).

**Comment by dormaayan** [comment]
Done

**Comment by dormaayan** [comment]
@NivShalmon  add user manual for the widget

**Comment by NivShalmon** [comment]
done
