### ISSUE TITLE
False errors in eclipse

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1409]
the code
```
boolean b1;
b1 = a != null && a.getOperator() == ASSIGN;
```
can be expanded to
```
boolean b1;
boolean b2 = a != null;
b1 = b2 && a.getOperator() == ASSIGN;
```
but in the expanded code eclipse gives an error saying we might get null pointer exception from a.getOperator(). What should we do with this case @yossigil ? Can we change the project properties to only warn on such case and not to give an error?

**Comment by yossigil** [comment]
Sure
