### ISSUE TITLE
Bug in spartan names

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Main#141]
``` java
  public static void go(final Object os[], final String... ss) {
    for (final String s : ss)
      out(s);
    out("elements", os);
  }
```

Renaming suggest 'o' rather than leaving as is
- [x] Create test method
- [x] Make the test fail
- [x] Fix the bug

**Comment by yossigil** [comment]
@dngreenst This is related to the code that you wrote in conjunction with #31

**Comment by dngreenst** [comment]
Appernately, the SingleVariableDeclaration of `Object os[]`, and any other c\c++ type array declarations, is not recognized as ParameterizedType. 

Extended the pluralVariadic function, to deal with this case too (previously, only added an extra "s" for varargs).

**Comment by yossigil** [comment]
@orimarco : can you integerate @dngreenst into our testing classes?

**Comment by orimarco** [comment]
@yossigil you mean testing classes of Lola?

**Comment by yossigil** [comment]
OOPS, I meant @OriRoth

**Comment by OriRoth** [comment]
@dngreenst you can contact me through Telegram about this issue (Ori Roth)... do you have a test class you need to integrate into TrimmerTest?

**Comment by yossigil** [comment]
@dngreenst make sure that the tests were not lost last night.

**Comment by dngreenst** [comment]
They were not transferred to TrimmerTest - moved them now. I see TrimmerTest250 was left unchanged - is this intentional? I did not delete my tests from it, in case it was.

**Comment by yossigil** [comment]
@OriRoth : what happened to TrimmerTest250? I presume you did not touch it.

**Comment by OriRoth** [comment]
It is untouched. Already talked with @dngreenst - we ask you to clarify where tests can be written and which test classes can be removed (mainly about TrimmerTest250).

**Comment by yossigil** [comment]
Good. TrimmerTest250 should not be touched.
I have a template testing class, that everyone should use as starting point.
https://github.com/SpartanRefactoring/Spartanizer/blob/master/src/test/java/il/org/spartan/spartanizer/AAA_TemplateTestTemplate.java


Mark if you have seen it:

- [ ] @dngreenst 

- [ ] @OriRoth 

- [ ] @sakopzon 

- [ ] @dormaayan 

- [ ] @NivShalmon 

- [ ]

**Comment by yossigil** [comment]
@dormaayan : did you see this?
@sakopzon : ?

**Comment by dormaayan** [comment]
@yossigil : yes, I did I can't mark it for some reason

**Comment by yossigil** [comment]
@sakopzon ?

**Comment by OriRoth** [comment]
Test class `Issue141.java` has failures. @dngreenst @dormaayan did one of you worked on it? Do you want to help me solve this?

**Comment by yossigil** [comment]
Seems as an initial search for searching why tests fail recently

**Comment by yossigil** [comment]
@SapirBismot ?

**Comment by SapirBismot** [comment]
@yossigil I'm working on it.. :+1:

**Comment by OriRoth** [comment]
@SapirBismot If you want you can tag this issue in your commits' messages, example:
```
woriking on #141
```
so everybody can see your progress when inspecting the issue. You can use it also to close the issue:
```
close #141
```
or
```
fix #141
```
or any other form:
```
finally fixed #141
```

**Comment by yossigil** [comment]
@OriRoth : your Karma explodes #169

**Comment by SapirBismot** [comment]
@yossigil I'm not really understand what I should do..

**Comment by SapirBismot** [comment]
@yossigil 
I noticed that saa in "final String saa" wasn't replaced, but s in "final String s" was replaced by ¢.
this is the bug? Are we need to prevent this replacement ?

**Comment by SapirBismot** [comment]
@yossigil ?

**Comment by OriRoth** [comment]
@SapirBismot it is recommended to describe spartanizations using code exmples:
```Java
The code before spartanization
```
=>
```Java
The code after spartanization
```
this is much clearer. You can edit your previous comments as well.

**Comment by yossigil** [comment]
@SapirBismot I saw your comment the other day. I trust that you can manage without me.

**Comment by yossigil** [comment]
@SapirBismot 

`@yossigil 
I noticed that saa in "final String saa" wasn't replaced, but s in "final String s" was replaced by ¢.
this is the bug? Are we need to prevent this replacement ?`

Can you please rephrase in the fashion of @OriRoth's message?

**Comment by SapirBismot** [comment]
@yossigil 
I noticed that
```
public static void go(final Object os[], final String... ss) {
  for (final String saa : ss) 
    out(saa); 
    out("elements", os);   
}
```
wasn't replaced, but
```
  public static void go(final Object os[], final String... ss) {
    for (final String s : ss)
      out(s);
    out("elements", os);
  }
```
==>
```
  public static void go(final Object os[], final String... ss) {
    for (final String ¢ : ss)
      out(¢);
    out("elements", os);
  }
```
I looked at the tipper ForRenameInitializerToCent and tried to understand it.

**Comment by yossigil** [comment]
Ok, now I understand your question. You should search for a function that determines whether a name is a generic name for a given type. The function should say that s1, s2, s, str, string, string1, string2, are all generic names for the type String.

If the code does not use this function, make it use it. If the function is not so clever to deal with all the examples, open a new Issue on it, and assign it to someone, e.g., @dormaayan , @OriRoth or me.

The bug you have is that 'saa' is not a generic name for String, and I do not see a way inwhich it is considered as one. So, fix the test, enable spartanization or whatever, and close the current issue.

**Comment by OriRoth** [comment]
Why are we using centification only for generic names? It is just an heuristic for meaningful renaming. If the heuristic fails (as in this case, because we *expected* renaming), maybe it should be changed (?).
I suggest renaming even for non-generic names if their *usage* is limited, i.e. under 5 uses or whatever.

**Comment by yossigil** [comment]
Here is the general direction I have: I supsect that it can be proved that most names are useless and the effort for making good name is wasted. to show that I want to develop a simple set of very clear rules which deterministically determine the name of a variable. this set shold be simple, and as extensive as possible.

**Comment by yossigil** [comment]
Dor, please study this. It may be defunct.
