### ISSUE TITLE
Correct nominal tippers' descriptions

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1413]
Some of them don't mention the correct new name (that has been chosen in the preferences page)

**Comment by dormaayan** [comment]
Couldn't find a convenient way to load dynamically the name to the description so I changed the description to be more general

**Comment by OriRoth** [comment]
What's the problem? You can get the names from store... Not crucial though.

**Comment by dormaayan** [comment]
@OriRoth , No I don't get them like that, I get them from a static field from nominal (I think...) and for some reasons the value it retrieves in the description method is not consistent with the actual one, but the renaming itself works just fine
