### ISSUE TITLE
fix spartanizer preferences page

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1414]
The widget operations choosing window appears under _Spartanization Tips_ preferences page instead of the project in workspace (it should appear only under Widget preferences page), check how it looks in the current version of the plugin (from marketplace) and in eclipse application

**Comment by ravivos** [comment]
This is a known bug - when pressing the "restore default" it fixes it.
On it to try and fix the bug forever, Thank you

**Comment by yuvalsimon** [comment]
My commit fixed this bug in the version from this morning, note that the preference page doesn't work
