### ISSUE TITLE
Error upon spawning new IntelliJ instance on RunIdea

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1422]
![screenshot from 2017-05-26 15-02-58](https://cloud.githubusercontent.com/assets/16507852/26496283/845d7b0c-422f-11e7-8725-9c21403f6c09.png)

**Comment by RoeiRaz** [comment]
It turned out to be a conflict between packages import by intellij-spartanizer and transitive dependencies imported from spartanizer-plugin. We excluded the problematic transitive dependencies in the build.gradle file, looks like it solves the problem

**Comment by OriRoth** [comment]
Why *intellij-spartanizer* is dependent on *spartanizer-plugin*? We have to make sure the relevant libraries are exported into sub-modules.
