### ISSUE TITLE
bug in type's baptize on primitives

### ISSUE THREAD

**Issue by NivShalmon** [SpartanRefactoring/Main#1424]
When calling baptize on a primitive before it has been initialized, a new baptized type will be created for that primitive. Once the primitive is initialized it will override the baptized type and baptize will work as intended, but because of this bug `baptize("int").eqauls(INT)` is false if INT was not initialized before.

**Comment by NivShalmon** [comment]
@yossigil I didn't find a nice way to make the enum intialize before baptize is called, so I went for something in the middle. The map is initialized as an anonymous class, but the values stored in it are decided in the enum's constructor, as they were before.

**Comment by yossigil** [comment]
NP
