### ISSUE TITLE
Move our Wikis to new Repo

### ISSUE THREAD

**Issue by amirsagiv83** [SpartanRefactoring/Main#1434]

**Comment by OriRoth** [comment]
Notice the Github wikis are managed by... git! You can use git manipulations to do this easily (see (here)[https://stackoverflow.com/questions/15080848/how-do-i-clone-a-github-wiki]).

**Comment by AnnaBel7** [comment]
Done.
All the wiki pages include IntelliJ in their names so that they will be easier to find.
