### ISSUE TITLE
Test the Plugin before 35th May

### ISSUE THREAD

**Issue by amirsagiv83** [SpartanRefactoring/Main#1435]
Each of you (except for Michal) will test all the tippers available on his OS.
Anna - MAC
Roey - Linux
Amir - Windows

Michal, please upload your example file that we will test the tippers on.
the test will be done this weekend after all other tasks are done.

Mark yourself when you're done.

- [ ] Roey

- [x] Amir

- [ ] Anna

**Comment by michalcohen** [comment]
I've uploaded the examples to a new Issue.  If someone is working on new tippers, once they are done an example should be added to this file

**Comment by AnnaBel7** [comment]
@michalcohen I tested the plugin on this file and had a few problems:
1. this:
    ![image](https://cloud.githubusercontent.com/assets/22842727/26694952/d54badea-4711-11e7-83b1-1673f9927232.png)

    turned into this:
    ![image](https://cloud.githubusercontent.com/assets/22842727/26694638/c73e4ff6-4710-11e7-94b7-132734cdd441.png)

2. this is not recognized:
    ![image](https://cloud.githubusercontent.com/assets/22842727/26695004/fa99ff98-4711-11e7-9c10-a2566d21a344.png)

**Comment by RoeyMaor** [comment]
Should the new tippers be included in the tests?

**Comment by amirsagiv83** [comment]
@orenafek , try to check the bug anna found in your tipper

**Comment by amirsagiv83** [comment]
The code you should test the tippers with is in the last comment in #1444 .
