### ISSUE TITLE
Implement New Tip: Fluent Setter

### ISSUE THREAD

**Issue by amirsagiv83** [SpartanRefactoring/Main#1436]

**Comment by orenafek** [comment]
Bug:
``` java
class X{
        private int x;

        public void setX(int x){
            this.x = x;
        }
    }
```

changes to :
``` java
class X {
        Pineapple.X setX(int x) {
            this.x = x;
            return this;
        }
    }
```

(is removes the data member itself :( )

**Comment by michalcohen** [comment]
Pineapple.X? Have you defined anywhere Pineapple?
And yes... this tipper isn't done yet because it dependents on Class basic block (which isn't done yet either...)

**Comment by orenafek** [comment]
Pineapple is the outer class, which is fine.
this tipper should be annotated with `@TipperUnderConstruction(INCOMPLETE)` in the meanwhile

**Comment by michalcohen** [comment]
Blocked by #1387
