### ISSUE TITLE
Create an "SpartaDefeet" annotation to eliminate the possibility of marking in the user code.

### ISSUE THREAD

**Issue by orenafek** [SpartanRefactoring/Main#1447]
When the user uses this annotation, its code isn't marked at all.

``` java

@SpartaDefeet
public class MyClass {
....
}

**Comment by amirsagiv83** [comment]
What is this?

**Comment by orenafek** [comment]
This should be an annotation that disables the spartanization on the entire file.

**Comment by amirsagiv83** [comment]
And did you work on it or is it just an idea?

**Comment by michalcohen** [comment]
Amiros, I believe you are the guy for this mission :D If you aren't available doing this issue, just unassign yourself, and if you need any more explanations, talk with me or with oren :)
@amirsagiv83

**Comment by orenafek** [comment]
Done :)
It is crucial that #1487 is solved to enable the maximum flexibility with this ability.
