### ISSUE TITLE
Bug in InfixMultiplicationSort

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1449]
```
int iis = 2;
int cc = (iis++)*(--iis);
```
goes to
```
int iis = 2;
int cc = --iis * iis++;
```

**Comment by NivShalmon** [comment]
@yuvalsimon @yossigil 
I've added a precondition that there are no increments/decrements in the expression to the tipper. However, this raises the question of whether we only want to not do this in the case of increment/decrement, or in any case of side effects (mostly method invocations). Disabaling the tipper whenever there are posibble side effects will realy weaken it, and break many tests, but leaving it be will cause cases such as `f()*x` to turn to `x*f()`,which may change the result depanding on f's side effects. Some tests test this specific behaviour though, so I wasn't sure what to do.

**Comment by OriRoth** [comment]
Yes you are right. I'll just drop an actual code for your example:
```Java
class A {
  int x;
  int f() { return x = 1; }
  int g() { return f() * x }
}
```

**Comment by yossigil** [comment]
Folks: there is a method that checks whether an expression has side effects or not
