### ISSUE TITLE
Request from the client-game: better use-case examples

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1456]
people requested an example snippet that they can start with, I think we should add a working code snippet that they can start with - with some meaningful use-caes.
We should also add it to the "what is athenizer" wiki

**Comment by OriRoth** [comment]
We may include it as a sanity check I guess.

**Comment by ravivos** [comment]
@yuvalsimon, what's up with this?

**Comment by ravivos** [comment]
@yuvalsimon... what's up?

**Comment by yuvalsimon** [comment]
I wrote some code but the spartanizer is broken @ravivos

**Comment by yuvalsimon** [comment]
@ravivos done:
https://github.com/SpartanRefactoring/Main/wiki/Experience-the-Athenizer-and-Spartanizer
