### ISSUE TITLE
Client-game requests: menu->athenize->current selection missing

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1457]
clients complained on missing current selection button.
we should either add it, or remove it from the "user guide" wiki

**Comment by OriRoth** [comment]
@tomerdragucki see `SingleFlater#limit(ITextSelection)`. You can get a text selection from a `Selection` object: `Selection.Util.current().textSelection`.
@ravivos we should decide the exact "selection" policy: the current scheme is to ignore any in/deflation option *outside* marked text, see `SingleFlater#inSelection(ASTNode)`.
