### ISSUE TITLE
Client-game conclusions

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1459]
primary conclusions from the other teams:
1. participants with mouse prefered the mouse wheel option, participants without a mouse prefered the shortcuts (ctrl+'-'/'+') on pressing the widget buttons.
2. participants enjoyed the pull/push in the widget button
3. participants said it was very useful

enhancements:
1. participants said it bothered them that they can not know whether the plugin is on or off (the Athenizer)

I am tagging all of you team mates so you can be impressed with the results, please like this so I can know you have seen the issue.
Also, we should find a way to make the enhancement be practical in our project.
One option might be - 2 different icons which show in the toolbar wether the plugin is on or off.
Another option (maybe we should implement both) might be showing a different label in the main menu.
Please comment your opinion

**Comment by OriRoth** [comment]
See #1473 and #1474.
