### ISSUE TITLE
Client-game conclusions

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1460]
conclusions from the 35th of may (to be addressed):
- [ ] possible: make plugin load in android studio
- [ ] make sure installation instructions require intellij 2017
- [ ] align the window of the playground correctly
- [ ] disable spartanizer - not clear
- [ ] add explenation of nano patterns to user guide
- [ ] the clear button in the playground is expected to clear everything
- [ ] make an interface that shows all possible tippers in the page
- [ ] possible: make code in the playground appear in a java coloring syntax
- [ ] "spartanize this" - not working on leonidas
- [ ] if there is a tip suggestion and also an intellij warning, the warning won't show.

**Comment by amirsagiv83** [comment]
I'm opening Issue to each task to organize it.
