### ISSUE TITLE
Figure out how to make the plugin compatible to older versions of IntelliJ

### ISSUE THREAD

**Issue by amirsagiv83** [SpartanRefactoring/Main#1462]
If its not possible, add info about the required version to the installation guide & readme.

**Comment by michalcohen** [comment]
Is it done and tested? @orenafek

**Comment by michalcohen** [comment]
@orenafek  ?

**Comment by orenafek** [comment]
Unfortunately, this is harder than I expected. Not done yet

**Comment by orenafek** [comment]
Fixed. :)
