### ISSUE TITLE
make code in the playground appear in a java coloring syntax

### ISSUE THREAD

**Issue by amirsagiv83** [SpartanRefactoring/Main#1467]

**Comment by amirsagiv83** [comment]
The key might be EditorEx class of IntelliJ

**Comment by OriRoth** [comment]
I think it is called *syntax highlighting*. Check whether [this](http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/syntax_highlighter_and_color_settings_page.html) is relevant.

**Comment by OriRoth** [comment]
This is the [source](https://github.com/JetBrains/intellij-community/tree/master/platform/editor-ui-api/src/com/intellij/openapi/fileTypes). It seems syntax highlighting is an extension point, so you may look for the plugin implementing it and call its implementing class or whatever.

**Comment by amirsagiv83** [comment]
Found a gradle project which looks like exactly what we need in the easiest way to do that!

[RSyntaxTextArea](https://github.com/bobbylight/RSyntaxTextArea)

**Comment by amirsagiv83** [comment]
@RoeiRaz

**Comment by RoeiRaz** [comment]
Done
