### ISSUE TITLE
If there is a tip suggestion and also an intellij warning, the warning won't show.

### ISSUE THREAD

**Issue by amirsagiv83** [SpartanRefactoring/Main#1468]
Also, a similar mechanism of eclipse warnings for applicable tippers should be added.

**Comment by RoeyMaor** [comment]
"a similar mechanism of eclipse warnings for applicable tippers should be added" - could you elaborate?
also, the warnings do show, both in the editor to the right, and upon compilation. the problem is merely the yellow underline that wont show?

**Comment by RoeyMaor** [comment]
as we spoke in the meeting, closing
