### ISSUE TITLE
Nano patterns prompt before adding SpartanizerUtils.java

### ISSUE THREAD

**Issue by amirsagiv83** [SpartanRefactoring/Main#1470]
Tom talked about the nano patterns adding the SpartanierUtils.java file and said that we should consider adding information about it on runtime.

my suggestion is, on the first time a nano pattern tipper is activated, a messagebox will pop, saying that a file will be added to the project with a short explanation about what and why.

What do you think?
@michalcohen @AnnaBel7 @orenafek @SharonKL @RoeiRaz @RoeyMaor

**Comment by michalcohen** [comment]
I think this is a good idea that is realy simple to implement.

**Comment by amirsagiv83** [comment]
Closed.
