### ISSUE TITLE
Save all icons in the project resources

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1482]
Seems like the icons places is not consistent on different eclipses. In SpartanizationOperation.java I get error for an icon that can not be resolved - `platform:/plugin/org.eclipse.team.cvs.ui/icons/full/obj16/changelog_obj.gif`
Maybe should save the icons in the project resources instead of using eclipse library? @OriRoth

**Comment by OriRoth** [comment]
Do we have a permission?...

**Comment by OriRoth** [comment]
This is first priority because Eclipse Oxygen just came out (🎉🎉🎉) and they changed the URL of some of the pictures we are using.

**Comment by ravivos** [comment]
I think we should indeed save the icons as part of our project, if it doesn't violate any permissions of eclipse etc

**Comment by yuvalsimon** [comment]
We can use _ISharedImages_ interface to access icons, but it has very limited collection:
http://1.bp.blogspot.com/-rLRCAAU3Z2o/T1Y7hEyBl_I/AAAAAAAAABY/xHiICgoZb8g/s1600/Sans+titre.png

**Comment by OriRoth** [comment]
Check it out... I think this photo is very old ;)

**Comment by OriRoth** [comment]
@michalcohen you probably should remove your project assignment (get ya hands off ma proparty).

**Comment by ravivos** [comment]
whats up?

**Comment by yuvalsimon** [comment]
@OriRoth should I change the widget operations to use _ISharedImages_?

**Comment by OriRoth** [comment]
What you want. We can use local images as well.

**Comment by yuvalsimon** [comment]
@OriRoth is it alright to save eclipse's icons in our project?

**Comment by OriRoth** [comment]
Not sure... probably no.

**Comment by OriRoth** [comment]
Design them yourselves.

**Comment by OriRoth** [comment]
This is not closed! We should do so for all icon, why stopping at the widget?

**Comment by OriRoth** [comment]
Mind `Dialogs.java` and `plugin.xml`.

**Comment by ravivos** [comment]
@yuvalsimon 
Icons are not good because some of them have a white bg instead of a transparent one
use [this](https://stackoverflow.com/questions/12945763/how-to-convert-the-background-to-transparent)
this is first prio, do ASAP
