### ISSUE TITLE
Add additional button to Menu: "Add Spartan Utils" 

### ISSUE THREAD

**Issue by orenafek** [SpartanRefactoring/Main#1487]
Upon click on this button, the sprtanUtils file will be added, and the button should be change to
**Update Spartan Utils** and should repaste it into the user's directory. This last requirement is crucial if the user had an older version of the plugin
This is crucial for the usefulness of the 
``` java
@SpartaDefeat
``` 
annotation as in #1447.

**Comment by amirsagiv83** [comment]
Closed.
