### ISSUE TITLE
Not allow adding widget operation with empty name

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1492]
Currently the user can add operations without entering a name, so need either default name or force the user to enter some name. Also should not allow adding operations with the same name.

**Comment by ravivos** [comment]
Thank you.
Also, I think it should not be named as an existing operation already either

**Comment by OriRoth** [comment]
What? The operation's name is chosen by the programmer, not the user. It may be empty and there may be duplicates.

**Comment by yuvalsimon** [comment]
But it's confusing to have operations with the same name or with empty name. Just like we don't allow too big widget size.

**Comment by ravivos** [comment]
@OriRoth, are you sure that we want to let the programmer (the client) which uses our plugin choose an empty or a duplicated name?

**Comment by OriRoth** [comment]
IDC

**Comment by ravivos** [comment]
empty name is not allowed anymore, duplications are because they still might differ by their configuration
