### ISSUE TITLE
Add wheel to add new widget operation window

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1493]
![image](https://user-images.githubusercontent.com/17455055/27207633-0293ca34-5249-11e7-8e15-013454d72476.png)
Can not see the last operation

**Comment by ravivos** [comment]
I made it resizable.
I think it's a better solution

**Comment by yuvalsimon** [comment]
It's not good @ravivos. Some people have tiny screen, and also if we add more operations it would be too much, and it doesn't look good if someone opens this window and sees half of some text. 
@OriRoth what do you think?

**Comment by yuvalsimon** [comment]
I checked it, just need to change from _Composite_ widget to _ScrolledComposite_, but it throws exception for the ListEditor (so it probably could happen also with the current _Composite_...)
