### ISSUE TITLE
Athenize toolbar button should not spartanize selection, only on/off

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1494]
Just separate the command in `plugin.xml` into two commands, and refer to their ids in `InflateHandler`.

**Comment by ravivos** [comment]
I think it should athenize the code, because it should be symmetric to it's neighbor toolbar button - the spartanizer

**Comment by OriRoth** [comment]
No, because now it represents the toggle state as well, so it should only be used for zooming on/off.

**Comment by ravivos** [comment]
I think we should add another tool bar button, with the athenizer ICON which will be the toggle button

**Comment by OriRoth** [comment]
[REFER](https://thefanaticalswordsman.files.wordpress.com/2011/06/pic_buttons.jpg)
