### ISSUE TITLE
Yet another inlining bug

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1495]
*Might be a duplication*
```Java
boolean b2, b3 = ownerType == null;
b2 = !b3 ? that.ownerType != null : !ownerType.equals(that.ownerType);
```
==>
```Java
boolean b2 = !b3 ? that.ownerType != null : !ownerType.equals(that.ownerType), b3 = ownerType == null;
```
`b3` is not recognized because it is defined later in the same variable declaration statement.

@dormaayan I need it fixed for the demostration
@ravivos this can easily cause bugs when zomming in/out, thus first priority

**Comment by dormaayan** [comment]
I'll do that

**Comment by dormaayan** [comment]
@OriRoth : In that case, we don't want to inline at all, right ?

**Comment by OriRoth** [comment]
Probably.

**Comment by OriRoth** [comment]
@dormaayan AHA! What do you think about this:
```Java
int a, b = 1;
a = b;
```
==>
```Java
int b = 1;
int a = b;
```
==>
```Java
int a, b = 1, a = b;
```

**Comment by OriRoth** [comment]
@tomerdragucki Raviv told me you want this issue. It is *urgent* so you have *today* only. The solution I proposed should work, and it make it much easier. Remember tests etc. etc.
