### ISSUE TITLE
Problem with comments

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1501]
the use of multiline comments in the code causes issues with tippers. for example:
![screenshot from 2017-06-18 12-21-07](https://user-images.githubusercontent.com/16507852/27259877-d43b28a6-5425-11e7-86b8-cff9a2d8913e.png)
activating the tipper in the situation above causes an exception.
another example, with a single comment before the relevant content, the tipper is okay:
![screenshot from 2017-06-18 12-56-59](https://user-images.githubusercontent.com/16507852/27259881-e566e7d2-5425-11e7-9dc6-718b8e04737c.png)
with another comment, the tipper won't recognize:
![screenshot from 2017-06-18 12-57-21](https://user-images.githubusercontent.com/16507852/27259886-f95c2446-5425-11e7-8288-0fcbf16bfd73.png)

**Comment by OriRoth** [comment]
You should check how PSI deals with comments in the node level. In ASTNode
for example comments are discarded by the compiler (whitespaces) but can be
created as nodes. Anyway, javadoc comments are part of the Java BNF, so
they should be ok.
