### ISSUE TITLE
Tips Configuration Windo is broken

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Main#1502]

**Comment by OriRoth** [comment]
What is the problem exactly? The only thing I saw is that one of the categories cannot be enabled.

**Comment by dormaayan** [comment]
I simply tried to import the spartanizer on the running plugin and to configure the active tippers, nothing happened and there were some errors in the console

**Comment by OriRoth** [comment]
So maybe it's a backward compatibility/sync issue... check it out.

**Comment by dormaayan** [comment]
Seems like it was only a local problem on my computer
