### ISSUE TITLE
bug in LocalInitializedNewAddAll

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1506]
```
public static Stats of(long... values) {
	StatsAccumulator acummulator = new StatsAccumulator();
	acummulator.addAll(values);
	return acummulator.snapshot();
}
```
goes to
```
public static Stats of(long... values) {
	StatsAccumulator acummulator = new StatsAccumulator(values);
	return acummulator.snapshot();
}
```
This constructor does not exist. The code is from guava->Stats.java

**Comment by NivShalmon** [comment]
This is a troublesome one. The only real way to prevent this is by using binding, but the spartanizer works without binding. We can work around this by hard-coding the classes we work on, though that would make the tipper weaker than the matching bloater that does use binding

**Comment by OriRoth** [comment]
Or just declare it as non core...

**Comment by yuvalsimon** [comment]
It's non core now

**Comment by yuvalsimon** [comment]
I'll keep it open to remember it if binding would be added to the spartanizer sometime

**Comment by OriRoth** [comment]
It won't

**Comment by OriRoth** [comment]
@yuvalsimon maybe tag this issue near the non-core declaration o it won't be removed.
```
... // see #1506
```
