### ISSUE TITLE
Write example for tips

### ISSUE THREAD

**Issue by michalcohen** [SpartanRefactoring/Main#1511]
Amir:
- [x] FluentSetter
- [x] MethodDeclarationRenameSingleParameterToCent

Roey:
- [x] ReplaceIdPlusOneWithIdPlusPlus
- [x] UnusedParameterToUnderscore

**Comment by amirsagiv83** [comment]
@RoeyMaor ,
I'll take the first two and you take the the others.
If you prefer otherwise, let me know
