### ISSUE TITLE
Leonidas tippers are dupplicated in tool box

### ISSUE THREAD

**Issue by michalcohen** [SpartanRefactoring/Main#1522]
For example, 'FluentSetter' appear twice.
@amirsagiv83  I think it was related to the controller, but I'm not sure. If you can't fix it, assign someone else :)

**Comment by amirsagiv83** [comment]
I can't reproduce the bug...
I also went over the algorithms of the toolbox to see if i can fins something but all seem right.
Im closing this and if anyone encounters this bug, we will reopen this issue.
