### ISSUE TITLE
Inlining fails

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#1523]
This should be fully inlined, i.e. no b# variables:
```Java
boolean b4 = Arrays.equals(actualTypeArguments, that.actualTypeArguments);
if (!b4)
	return false;
boolean b5, b7 = ownerType == null;
b5 = !b7 ? that.ownerType != null : !ownerType.equals(that.ownerType);
return !b5 && (rawType == null ? that.rawType == null : rawType.equals(that.rawType));
```
@SpartanRefactoring/zoomers

**Comment by OriRoth** [comment]
There are several tippers involved here. `b4` should be inlined, simple stuff. `b7` should be inlined, followed by combining `b5`'s definition and initialization then its (final) inlining into the return statement.

@NivShalmon want to take it as a challenge?

**Comment by yuvalsimon** [comment]
Note that in the current release it is fully inlined

**Comment by OriRoth** [comment]
I don't care about current release, I care about current status.

**Comment by OriRoth** [comment]
It is probably a one-line-fix BTW.

**Comment by yuvalsimon** [comment]
Your suggestion in #1495 solves this, if you replace the declarations order of b5 and b7 you'll end up with this:
```
return Arrays.equals(actualTypeArguments, that.actualTypeArguments)
    && ownerType != null ? that.ownerType == null : ownerType.equals(that.ownerType)
    && (rawType == null ? that.rawType == null : rawType.equals(that.rawType));
```

**Comment by NivShalmon** [comment]
I just tried this in the current build using the default enabled tipeprs and it is fully spartanized

**Comment by NivShalmon** [comment]
I forgot to pull, this indeed doesn't work now. I'll implement a tipper to do @OriRoth's suggetion from #1495 and that should solve this

**Comment by OriRoth** [comment]
No, you should just replace the current's implementation - then other tippers should do the rest.
