### ISSUE TITLE
List of bugs in git push/pull/commit

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1531]
Writing here a list of bugs I found when using the git push/pull/commit from widget (which is by the way very convenient and would probably be a great feature in our plugin excluding the bugs):

1. git pull says "pulled successfully" even when project is up to date and there is nothing to pull.
2. git push says "pushed successfully" even when there is no commit to push
3. git commit should have a default option to open a dialog with a text box to enter the commit name  rather then always use Sync (should probably be made as a new operation which is called 'git manual commit').
4. (least important bug in my opinion) git commit always has something to commit, even when pressing twice in a row, meaning no changes where detected - probably because of adding newline

**Comment by tomerdragucki** [comment]
Number 4 is as a result of jgit ignoring the local conf which does autocrlf. There's a separate issue for that. I handled 1 and 2 in my last commits.
