### ISSUE TITLE
when text selected - should zoom *only* selected 

### ISSUE THREAD

**Issue by ravivos** [SpartanRefactoring/Main#1532]

**Comment by OriRoth** [comment]
Did you implemented this? @ravivos

**Comment by OriRoth** [comment]
No you did not. If you close an issue without solving it *directly*, please say so.

**Comment by ravivos** [comment]
Because it is already implemented, though zooms only once, which is fine and correct

**Comment by OriRoth** [comment]
Not using the mouse wheel!
