### ISSUE TITLE
Unsafe if-inversion

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1535]
Consider this case:
```
if(cond1) {
  if(cond2)
    ... (#1)
}
else if(cond3)
  ... (#2)
else if(cond4)
  ... (#3)
```
When using subject.pair(elze,then).toNot(cond1) it does not consider the inner if statement (cond2) which would be concatenated with other ifs this way: 
```
if(!cond1)
  if(cond3)
    ... (#2)
  else if(cond4)
    ... (#3)
  else { 
   if(cond2)
    ... (#1)
  }
```
In this case need to enclose the statement under if(!cond1) in a block, which then give us:
 ```
if(!cond1) {
  if(cond3)
    ... (#2)
}
else if(cond4)
  ... (#3)
else {
 if(cond2)
  ... (#1)
}
```
There are similar cases when the original if is not enclosed in block and when both if and else are not enclosed in blocks.

**Comment by OriRoth** [comment]
Great analysis. This should be dealt with as with if-brackets-removal.

**Comment by yuvalsimon** [comment]
done in 51a772aed9f6c047303cb91d2933b827b5dc78d4
