### ISSUE TITLE
Tipper debugging

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1538]
Everyone (who are not on vacation) should run the test TestAllTippers and see what they can fix.
also, it's important to pay attention to the examples written. many times a ; is forgot, or an access modifier that exists in the key but not in the value, variable names are written inconsistently etc. such things cause false alarms. please test the validity of your examples before pushing.

you can choose to crash upon the first failure, or show all problems, via the TipperTest constructor vairables.

**Comment by amirsagiv83** [comment]
Specific issues will be opened for each failing tipper.
