### ISSUE TITLE
Tipper dropout. How come we lost so much.

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Main#1545]

**Comment by yuvalsimon** [comment]
@yossigil Raviv and I checked it, seems alright. 
On guava project:
* With version 2.6.3 we got 13777 tips applied and ended up with 148713 lines of code
* With the current version 13873 tips applied, and ended up with146124 line of code  

In the original guava project there are 155944 lines of code (I counted all lines in the src folder, didn't exclude comments)

**Comment by yossigil** [comment]
Thanks @OriRoth
