### ISSUE TITLE
Infinite renaming tippers apply

### ISSUE THREAD

**Issue by yuvalsimon** [SpartanRefactoring/Main#1550]
MethodDeclarationRenameSingleParameter and ParameterAbbreviate don't stop being applied (in guava project). @dormaayan You worked on renaming
These tippers change some names alternately, try this:
```
public String join(Iterable<? extends Entry<?, ?>> es) {
  return join(es.iterator());
}
```
(from guava->Joiner)

**Comment by ravivos** [comment]
@dormaayan , what about it?
should we cancel all those tippers or will you fix it ASAP?
 we need to release

**Comment by OriRoth** [comment]
We are here at the Technion and the release is drinking exotic beverages in the Maldives.

**Comment by dormaayan** [comment]
Done

**Comment by yuvalsimon** [comment]
@dormaayan  you broke more than 30 tests and we are right before release

**Comment by dormaayan** [comment]
@yuvalsimon : Sorry, I was in rush so I forgot about the tests, fixed.
