### ISSUE TITLE
exception upon disabling spartanization in current file, and then enabling it back again via the menu

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1554]
![screenshot from 2017-06-27 16-14-03](https://user-images.githubusercontent.com/16507852/27589324-b836574a-5b53-11e7-9873-57426a9191e6.png)

**Comment by amirsagiv83** [comment]
You got this exception because you tried to press the button and your cursor want's focused on a certain file in the editor.

I'ts not a bug, I'll just catch the exception and ignore it.
