### ISSUE TITLE
Installing the project

### ISSUE THREAD

**Issue by tomnof** [SpartanRefactoring/Main#1576]
It is not specified, or I didn't find it in the installation wiki - what should I do after downloading the JAR ?

**Comment by NivShalmon** [comment]
which project do you test, the athenizer or leonidas?

**Comment by tomnof** [comment]
athenizer

**Comment by RoeyMaor** [comment]
im also testing it, and found it here https://github.com/SpartanRefactoring/Main/wiki/Athenizer-Plugin-TL;DR

**Comment by NivShalmon** [comment]
Specifically in this issue https://github.com/SpartanRefactoring/Main/wiki/Installation-instructions
in the installing from a jar part

**Comment by tomnof** [comment]
after I put the jar in the dropin folder and started Eclips - nothing happened. What next?

**Comment by tomnof** [comment]
it's here. easy to miss
