### ISSUE TITLE
Added notification that plugin was installed successfuly 

### ISSUE THREAD

**Issue by AviadCo** [SpartanRefactoring/Main#1578]
After putting the jar file in the eclipse/dropins folder and running eclispe there is no notification that the plugin was installed succesfuly. is there anyway to add such one?

**Comment by NivShalmon** [comment]
no, but you can tell it worked by the addition of the spartanizer menu and some buttons to the toolbar

**Comment by AviadCo** [comment]
@NivShalmon  - i don't find all the symbols  which mentioned in the WIKI (e.g. Toggle Athenizer)

**Comment by yossigil** [comment]
@AviadCo : You are not supposed to contact people by phone.

**Comment by NivShalmon** [comment]
do you see the `Spartanizer `menu next to the `Refactor`? Also, what version of eclipse and what operating system are you using>

**Comment by AviadCo** [comment]
eclipse version:

Eclipse IDE for Java Developers

Version: Neon.1a Release (4.6.1)
Build id: 20161007-1200

Operation System: Ubonto 16.04

And i can see the  Spartanizermenu next to the Refactor.

**Comment by NivShalmon** [comment]
can you post a print screen of your eclipse? how the menus and toolbar look right now

**Comment by AviadCo** [comment]
i can't post a screenshot.. the tab is closed when i take the screenshot (automatically...) 
i when i click on Spartinizer tab -> Athenizer -> {
Athenize
Selection
Window
Project
}

i can't see Toggle Athenizer

**Comment by tomerdragucki** [comment]
Added to Installation wiki a pic for knowing that the plugin was installed.

**Comment by NivShalmon** [comment]
All of the athenizer options are under the Athenize sub menu

**Comment by NivShalmon** [comment]
Which wiki mentationed the Toogle Athenizer button without mentioning the Athenizer menu?

**Comment by AviadCo** [comment]
![untitled-1](https://user-images.githubusercontent.com/12224702/27769245-a3666830-5f2e-11e7-89e1-1a9d22ee9936.jpg)

https://github.com/SpartanRefactoring/Main/wiki/Athenizer

**Comment by NivShalmon** [comment]
It says to press the button in `Spartanizer->Athenize->Toggle Athenizer`, not `Spartanizer->Toggle Athenizer`
