### ISSUE TITLE
Athenizer not working on eclipse for Java EE

### ISSUE THREAD

**Issue by ArthurSap** [SpartanRefactoring/Main#1580]
I think if the spartanizer works on eclipse for Java EE so should the athenizer.

**Comment by ArthurSap** [comment]
Oh and I cant put any lables/milestones on issues

**Comment by NivShalmon** [comment]
What do you mean not working? Does the installation fail? Does it not expand the code properly? What did you do (step by step) and how did it fail?

**Comment by ArthurSap** [comment]
Uninstall previous Spartanizer plugin
Restart eclipse (and then close it)
Put the jar in the dropins folder
Open eclipse
Nothing happened (nor any buttons appeared).

**Comment by NivShalmon** [comment]
Then unfortunately I have to say we don't support Java EE at the moment and you should install the regular IDE for java to test our plugin.

**Comment by ArthurSap** [comment]
Oh god why
Oh well

**Comment by yuvalsimon** [comment]
@ArthurSap  It worked in my computer, make sure you put the jar in eclipse/dropins

**Comment by yossigil** [comment]
Good job @yuvalsimon @AdiOmari

**Comment by ArthurSap** [comment]
I put it there and it didn't work (Eclipse Neon 1 for Java EE)
But when I put it on the regular eclipse (Eclipse Oxygen) it worked
