### ISSUE TITLE
Error when trying to install QJoyPad

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1581]
![screenshot from 2017-07-02 13-19-14](https://user-images.githubusercontent.com/16507852/27769014-789acf38-5f29-11e7-9ff4-85a4fcdb7653.png)

Couldnt find which lib to install from the QJoyPad site, will continue looking

**Comment by dormaayan** [comment]
@RoeyMaor I think that's the right link: [here](http://qjoypad.sourceforge.net/#download)

**Comment by RoeyMaor** [comment]
This is what i followed.
The instructions say that to install i need to run ./config, then make, then make install.
The error above was when i ran ./config. I googled and found out the libraries to download. I followed the link and downloaded the latest QT library, but when i run make, i get a compilation error: 
![screenshot from 2017-07-02 13-28-29](https://user-images.githubusercontent.com/16507852/27769139-0cdfd718-5f2c-11e7-971c-9e477204fa01.png)

**Comment by dormaayan** [comment]
@RoeyMaor , We don't support problems regrading the installation of Joystick Key-Binding, you can try to find another Joystick Key Binding Programs online

**Comment by RoeyMaor** [comment]
If i understand correctly, the joystick is only used as a cool key binding, meaning i could use all the features without it, correct?

**Comment by dormaayan** [comment]
Right, you can simply use your keyboard and mouse wheel in order to make those operations
See wiki pages

**Comment by yossigil** [comment]
Good job @dormaayan
