### ISSUE TITLE
Athenizer causes compilation errors

### ISSUE THREAD

**Issue by AviadCo** [SpartanRefactoring/Main#1582]
To recreate bug:

git clone https://github.com/TechnionYP5777/SmartCity-Market.git

run Athenizer of all project on Employee project.

Here is a screenshot of the compilation error:

https://www.dropbox.com/s/jak3hm4y1u1rs13/photo_2017-07-02_13-36-55.jpg?dl=0

**Comment by ravivos** [comment]
There is no "Athenizer on all project"...
how did you run the athenizer on all project?

**Comment by AviadCo** [comment]
Spartinzier -> Athenize... -> Project

**Comment by NivShalmon** [comment]
where did you install the plugin from?

**Comment by ravivos** [comment]
@AviadCo , did you uninstall the previous version you add, follow the installation instructions and download the JAR file + add it to your dropins folder?

**Comment by yuvalsimon** [comment]
@AviadCo It works for me (with the last release):
![image](https://user-images.githubusercontent.com/17455055/27769297-b8ee49ce-5f2f-11e7-8901-a42ebe8b8799.png)
This is the code from your image
Maybe you don't have the last release?
(The error is because I don't have JavaFX I think)

**Comment by ravivos** [comment]
I guess you downloaded the latest release and now it's working, right? 💯
