### ISSUE TITLE
I am unable to understand any of the options

### ISSUE THREAD

**Issue by Kolikant** [SpartanRefactoring/Main#1584]
![image](https://user-images.githubusercontent.com/23051198/27769255-bf3bcd66-5f2e-11e7-8e51-c767bba25d0e.png)

the names don't mean anything to me and there isn't an explanation on them, the only way to understand what each one does is through trial and error and that's just not nice :(

**Comment by RoeyMaor** [comment]
Have you tried to install the relevant release from this repo?

**Comment by Kolikant** [comment]
I installed from the eclipse plugin, is that not the updated version?

**Comment by amirsagiv83** [comment]
in the installation menu in the wiki in this repo you can find exactly how to install the plugin.
https://github.com/SpartanRefactoring/Main/wiki/IntelliJ-Install-Me

**Comment by amirsagiv83** [comment]
![image](https://user-images.githubusercontent.com/15860047/27769302-c66f523c-5f2f-11e7-97d9-2ceb28250a36.png)
