### ISSUE TITLE
no button to clear code in the playground

### ISSUE THREAD

**Issue by Kolikant** [SpartanRefactoring/Main#1585]
it just allows to clear the spartanization result.
but if clicking the "Spartanize" button already overwrites it, then why does the clear button remove the result rather than the code to be spartanized? it seems to me that the code to be spartanized would be the one which we would like to be cleared

**Comment by RoeyMaor** [comment]
The clear button clears all of the code, you have installed the version from the old repo

**Comment by amirsagiv83** [comment]
Again, your'e working with the wrong release! take the latest release from this repo!
