### ISSUE TITLE
not replacing always true statement with removing the if

### ISSUE THREAD

**Issue by Kolikant** [SpartanRefactoring/Main#1586]
I made exceptionally stupid code

![image](https://user-images.githubusercontent.com/23051198/27769261-ea70f1be-5f2e-11e7-98a4-1a8c2c01dae8.png)

however, even though the statement is always true, spartanization left it in

![image](https://user-images.githubusercontent.com/23051198/27769265-f213c81a-5f2e-11e7-844e-0bb26ed96d92.png)

**Comment by amirsagiv83** [comment]
We don't have a tipper for this particular situation. IntelliJ already has a built in inspection that checks for this and is enabled by default so we decided to leave this out.
