### ISSUE TITLE
Leonidas\Spartanizer ignoring order of operations

### ISSUE THREAD

**Issue by leyaniv** [SpartanRefactoring/Main#1588]
the following lines of code:
```
static LocalTime rowIndexToLocalTime (int rowIndex){
    return LocalTime.of((rowIndex/HOUR_CHUNKS)+FIRST_HOUR, (rowIndex%HOUR_CHUNKS)*(60/HOUR_CHUNKS));
}
```

were changed to this:
```
static LocalTime rowIndexToLocalTime (int rowIndex){
    return LocalTime.of(rowIndex / HOUR_CHUNKS + FIRST_HOUR, 60 * rowIndex / HOUR_CHUNKS % HOUR_CHUNKS);
}
```

causing unexpected results

**Comment by RoeiRaz** [comment]
@leyaniv We weren't able to reproduce this bug. Are you sure you are using the latest release? (from https://github.com/SpartanRefactoring/Main/releases)

**Comment by leyaniv** [comment]
It happened to me at home using eclipse and the plugin from the marketplace (downloaded about 2 weeks ago).
I'll be able to test it again on tonight. 
This issue might not be related to "Leonidas" (I wasn't aware of the difference between the projects)

**Comment by RoeyMaor** [comment]
You are talking about the eclipse spartanizer for eclipse, this is not our project.
Refer to the installation guide of leonidas:
https://github.com/SpartanRefactoring/Main/wiki/IntelliJ-Install-Me
