### ISSUE TITLE
Tabs in playground aren't transferring correctly

### ISSUE THREAD

**Issue by ZivIzhar** [SpartanRefactoring/Main#1589]
![image](https://user-images.githubusercontent.com/16669466/27769445-dc567272-5f31-11e7-86a4-bc1c5670b0b4.png)

**Comment by RoeyMaor** [comment]
This is not the current version of the plugin. please follow the installation instructions https://github.com/SpartanRefactoring/Main/wiki/IntelliJ-Install-Me

**Comment by ZivIzhar** [comment]
![image](https://user-images.githubusercontent.com/16669466/27787986-7830c3ba-5fef-11e7-87c5-d9b9c02ee5bc.png)
A little better, but still all tabs are being removed!

**Comment by ZivIzhar** [comment]
The Code:

```
public class HelloWorld {

    public static void main(String[] args) {
        // Prints "Hello, World" to the terminal window.
        String abc = "Hello";
        System.out.println(abc);
    }

}
```

**Comment by RoeyMaor** [comment]
fixed it
