### ISSUE TITLE
Bug with multiple error catch

### ISSUE THREAD

**Issue by ArthurSap** [SpartanRefactoring/Main#1590]
I used a code that runs on java 7 (there was no requirement for java 8) with multiple errors:
```
		try {
			gn.generate(args);
		} catch (ClassNotFoundException e) {
			System.out.println(e);
		} catch (InvocationTargetException e) {
			System.out.println(e);
		} catch (IllegalAccessException e) {
			System.out.println(e);
		} catch (InstantiationException e) {
			System.out.println(e);
		} catch (NoSuchMethodException e) {
			System.out.println(e);
		}
```
and got this:
`try {gn.generate(args);} catch (NoSuchMethodException | InstantiationException | IllegalAccessException | InvocationTargetException | ClassNotFoundException ¢){System.out.println(¢);}`

With the following error:
`Multi-catch parameters are not allowed for source level below 1.7`

**Comment by dormaayan** [comment]
@ArthurSap: You are right, this specific tipper can't be applied while compiling with Java 7. 
You can simply disable the specific tipper by Right Click on the project, choosing "Spartanizaition Preferences" under Refactoring
