### ISSUE TITLE
Athenize current selection not working - no binding in current selection

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1593]
for example:
![image](https://user-images.githubusercontent.com/16507852/27786953-d7f49e7e-5feb-11e7-9e1d-7d8fb3969bbd.png)
happens with other examples too

**Comment by OriRoth** [comment]
It seems there is no binding in "current selection", we will solve it in the next release. In the meanwhile, use the mouse wheel/zoom the entire document in order to zoom this statement out.

**Comment by tomerdragucki** [comment]
Fixed. Thanks Roey! Will be available in the next release later today.
