### ISSUE TITLE
Please give me permission to write wiki (Leonidas). tnx

### ISSUE THREAD

**Issue by LiorBenAmi** [SpartanRefactoring/Main#1594]

**Comment by SharonKL** [comment]
@OriRoth

**Comment by LiorBenAmi** [comment]
. . .

**Comment by RoeyMaor** [comment]
Regarding the wiki permissions - non of our team members are admins for this repo, we have tried to contact the admin @OriRoth to get you permissions, and are still trying. anyways, in the meantime you can open an issue where you will write your report.
