### ISSUE TITLE
no, back to default button in toolbox

### ISSUE THREAD

**Issue by Kolikant** [SpartanRefactoring/Main#1595]
the toolbox is great and has intuitive explanations. however, when I opened the spartanizer the first time, it had some sort of default choices, only having about half selected and half unselected.

I selected all in order to test everything, but now I don't have a way to return back to the default configurations of when the application has started.

maybe if it had some starting configurations, there should be a way to go back to them should changes occur?

**Comment by RoeyMaor** [comment]
The default configuration is the one where all tippers are active. there exists a button "select all" which de-facto acts as a back-to-default (since the default is that everything is checked). In the release we published here only some tippers were marked by default, but that wasn't our intention.

**Comment by Kolikant** [comment]
oh, that's why I thought a default option existed then. thanks
