### ISSUE TITLE
analyze file not as informative as the toolbox

### ISSUE THREAD

**Issue by Kolikant** [SpartanRefactoring/Main#1597]
the toolbox has great information and examples as to what each tipper means, however when you choose to analyze a file, you would get this 
![image](https://user-images.githubusercontent.com/23051198/27787503-9cdaba6a-5fed-11e7-894e-d4a28b6d8a92.png)

without the ability to see here what each tipper would mean, proving difficulty in making sense of what to choose.

having clicking on the options, take you to the line is great, but niether in the code nor the analyze option can I see what it would do, making it uncomfortable for usage.

**Comment by amirsagiv83** [comment]
As you can understand this is not a bug. It's just a design decision we've made.
We would love it if you write your suggestion for giving more information in this window in your wiki report.

**Comment by Kolikant** [comment]
you got it
