### ISSUE TITLE
Update your old repo that it's outdated

### ISSUE THREAD

**Issue by ZivIzhar** [SpartanRefactoring/Main#1599]
readme.md and stuff

**Comment by orenafek** [comment]
Thank you for this comment. 
You're absolutely right!
@SharonKL  is working on it.

**Comment by SharonKL** [comment]
@orenafek & @ZivIzhar are on it

**Comment by SharonKL** [comment]
Updated, thanks @orenafek:
https://github.com/TechnionYP5777/Leonidas-FTW/blob/master/README.MD

**Comment by orenafek** [comment]
![image](https://user-images.githubusercontent.com/15859817/27787976-72f95a06-5fef-11e7-9c07-5e3d6b129e76.png)
