### ISSUE TITLE
Zoom in / Zoom out once from the menu not working

### ISSUE THREAD

**Issue by RoeyMaor** [SpartanRefactoring/Main#1600]
Am I using it correctly?
I tried to place my caret somewhere and then activate it from the menu, also tried marking the relevant code and then activating.
for example:
![screenshot from 2017-07-03 12-51-40](https://user-images.githubusercontent.com/16507852/27787973-6a543dd0-5fef-11e7-97bb-9f31021eaff7.png)

**Comment by tomerdragucki** [comment]
Hey Roey! You are using it correctly (marking code and then activating). We fixed this right now and this will be added to our release later today. Thanks.
