### ISSUE TITLE
Zooming in on several methods and zooming out on one.

### ISSUE THREAD

**Issue by ArthurSap** [SpartanRefactoring/Main#1601]
I tried to zoom in on several methods, and then to zoom out only on a single one. I put the courser on the method I wanted to zoom out on one (it was one of the first I zoomed in on) with the mouse scroll is zoomed out on the latest. Is this how it should be?

**Comment by dormaayan** [comment]
@ArthurSap : The Zoom in Zoom out scroller is working from top down of the file or from down to up. That's how it should be
