### ISSUE TITLE
Bug: No stopping point to the expension (Atanizer)

### ISSUE THREAD

**Issue by EliaTraore** [SpartanRefactoring/Main#1602]
If you press the atanizer button enough times, you'll get a code that doesn't compile - 

![bug_atanizer](https://user-images.githubusercontent.com/15971916/27770336-9916d61e-5f45-11e7-9aad-fd69d2f7b2d7.gif)

**Comment by NivShalmon** [comment]
Thank you for your support and detailed bug report.
This is a known bug, related to #1339. This happen because you press the button too fast. Put in backlog for now

**Comment by EliaTraore** [comment]
Fyi, this also happen with the button and not only in the widget
