### ISSUE TITLE
No example in LambdaExpressionRemoveRedundantCurlyBraces

### ISSUE THREAD

**Issue by ZivIzhar** [SpartanRefactoring/Main#1604]
![image](https://user-images.githubusercontent.com/16669466/27788688-409d7238-5ff2-11e7-93b4-8d8302193335.png)
![image](http://i0.kym-cdn.com/photos/images/newsfeed/000/173/576/Wat8.jpg?1315930535)

**Comment by orenafek** [comment]
This is shameful.
@SharonKL can you deal with it ?

**Comment by ZivIzhar** [comment]
Also LispLastElement
@SharonKL

**Comment by AnnaBel7** [comment]
Examples were added
