### ISSUE TITLE
Spartanize Current File Doesn't Work

### ISSUE THREAD

**Issue by dormaayan** [SpartanRefactoring/Main#1605]
While I'm trying to Spartanize current file, it seems like being stuck in an infinite loop and an IDE error is thrown

**Comment by RoeiRaz** [comment]
Hi, could you add a pastebin of the file you tried to spartanize + the exception trace, if possible?

**Comment by dormaayan** [comment]
Yes, it's actually my assignment in Software Design which can be found [here](https://github.com/dormaayan/software-design-3)

Try it over `SubscriberInitializerImpl.java`

**Comment by amirsagiv83** [comment]
fixed
