### ISSUE TITLE
[Final] Athenizer widget won't come up

### ISSUE THREAD

**Issue by tomnof** [SpartanRefactoring/Main#1606]
I used the git push option, got a success message (not sure why, I haven't pushed anything, would expect to get a relevant message), and when I tried to re-open the widget again, I couldn't - nothing happened. Only after Eclipse restart, it worked again.

**Comment by tomerdragucki** [comment]
Hey Tom, thanks for opening the issue! We fixed the wrong git message issue and it'll be available in our next release later today. As for the widget not coming up issue, we still didn't manage to recreate it.
