### ISSUE TITLE
Leonidas saying "Spartanize this!" twice on mouse hover

### ISSUE THREAD

**Issue by leyaniv** [SpartanRefactoring/Main#1607]
Is this suppose to happen?

![image](https://user-images.githubusercontent.com/11694372/27789047-9410afa6-5ff3-11e7-890c-5dadf5337ccc.png)

Also, I still do not have permission to edit your wiki

**Comment by RoeyMaor** [comment]
Regarding the wiki permissions - non of our team members are admins for this repo, we have tried to contact the admin @OriRoth to get you permissions, and are still trying. anyways, in the meantime you can open an issue where you will write your report.
Regarding the annotation description that appears twice - this is a bug in the annotation engine of intellij, and we have no control over it.
