### ISSUE TITLE
double clicking MethodDeclarationChangeSingleParameterToCent displays white screen 

### ISSUE THREAD

**Issue by Kolikant** [SpartanRefactoring/Main#1608]
![image](https://user-images.githubusercontent.com/23051198/27789468-6d36d8ea-5ff5-11e7-812e-159dc4dd57db.png)

waited 2 minutes, closes, tried again, waited two minutes, same result. empty screen

**Comment by amirsagiv83** [comment]
This bug is fixed. the same issue was opened yesterday... we just didnt publish a new release.
Thanks
