### ISSUE TITLE
The Add New Tipper window has UI problems

### ISSUE THREAD

**Issue by ZivIzhar** [SpartanRefactoring/Main#1609]
First, it slides out of my screen:
![image](https://user-images.githubusercontent.com/16669466/27790018-5e4eca34-5ff7-11e7-8a5f-4f556348c3af.png)

Second, the window has no name

**Comment by SharonKL** [comment]
done @ZivIzhar 

![image](https://user-images.githubusercontent.com/22201290/27790244-5e2faab8-5ff8-11e7-94c8-01cb1da8849b.png)

**Comment by OriRoth** [comment]
איזה בכיין אתה זיו זה משהו

**Comment by OriRoth** [comment]
No no you are alright, all bugs are important.
