### ISSUE TITLE
The enable/disable button defaults to “Enable spartanization” although the spartanizer is enabled by default

### ISSUE THREAD

**Issue by AdiOmari** [SpartanRefactoring/Main#1614]
![2](https://user-images.githubusercontent.com/5457431/27790428-077bcc3c-5ff9-11e7-97d0-9e6f620b7bb1.png)

**Comment by AnnaBel7** [comment]
@AdiOmari It seems you are using an old release. This was fixed in newer releases. [The new release](https://github.com/SpartanRefactoring/Main/releases/tag/SpartanizerJ1.2).
