### ISSUE TITLE
When trying to run undo - there are too many undos and i can't recover the original

### ISSUE THREAD

**Issue by AviadCo** [SpartanRefactoring/Main#1617]
Add feature to recover file

**Comment by ravivos** [comment]
Thank you, we will take it into consideration, maybe something to think about.
Mean while, you can use the athenizer to get some more "weight" to your code.
Did you try athenizing after spartanizing?

**Comment by OriRoth** [comment]
Check out the "Athenizer" preferences page. In there you'll be able to check "compound zooms" option which consolidate zoom operations.
