### ISSUE TITLE
Is this project dead? If so, could at least the Eclipse update site issue be fixed?

### ISSUE THREAD

**Issue by hanneshorn** [SpartanRefactoring/Main#1624]

**Comment by OriRoth** [comment]
Vise versa, the project is alive yet the update site have seen better days. I promise you will be notified whether this issue (faculty servers policy changes) is solved. I close this issue, you may stay tuned to #1622.

**Comment by yossigil** [comment]
@OriRoth : please do it

**Comment by hanneshorn** [comment]
New version 2.13.5: with spartan jar file in eclipse dropins folder and starting eclipse with -clean doesn't appear to do anything.
A couple of releases back a Spartan menu used to show under "Window-Preferences-Java" (if I recall correctly). Is the Spartan menu somewhere else now?

**Comment by OriRoth** [comment]
@hanneshorn it is probably a problem with the manual plugin installation. There is a new top menu option called `Spartanizer`, everything has been moved there.

**Comment by OriRoth** [comment]
The [update site](http://spartan.cs.technion.ac.il/site/) for the plugin specified at the Eclipse marketplace is on again! You can install the plugin in the usual way.
* The newest version will be uploaded somewhere in the future
* This project is not dead
