### ISSUE TITLE
Expand boolean expressions

### ISSUE THREAD

**Issue by OriRoth** [SpartanRefactoring/Main#980]
```Java
return x && y() || z;
```
==>
```Java
boolean a = x && y();
return a && z;
```
==>
```Java
boolean a = x;
a = a && y();
return a && z;
```
Usage of namespace is required.
Not only in return statements (?). Probably also in if statements.

**Comment by yossigil** [comment]
why should boolean be different from any other expression?

**Comment by OriRoth** [comment]
The type is well known. for other primitives we got an ambiguity for some operations (such as `+` for Strings/long/int/etc.). And we need the type in order to create a new variable.
Nevertheless, we can use `environment` to solve some of the issues, or at least to expand the expressions partially.

**Comment by yossigil** [comment]
As I thought the name space analysis is essential. Will see what **I** can do about this.

**Comment by mdoron** [comment]
I agree with @yossigil, this should work for other types as well. The Athenizer helps us with debugging, so we would like to take an expression such as (when all integers for example):
`a = b*c + d*e;`
and convert it to
```int tmp1 = b*c;
a = temp1 + d*e;```
and then
`int tmp1 = b*c;
int tmp2 = d*e;
a = temp1 + tmp2;`

**Comment by OriRoth** [comment]
@mdoron you cannot assume `int` will fit here.
When using *binding* it is possible to generalize this Expander to all (?) types.

**Comment by yossigil** [comment]
Kind of funny that this infrastructure issue pops out 12 hours before the deadline. @ravivos : FYI...

**Comment by ravivos** [comment]
@yossigil 
This issue is not related by any means to our goals for the past week.
In addition, the prototype had been pre-realesed yesterday at about 11pm - a day before what we planned in advance

**Comment by yossigil** [comment]
@ravivos Humans are mortal...

**Comment by mdoron** [comment]
@OriRoth, I assumed that in this example all were integers. Of course in the general case we would need to identify the actual type...

**Comment by yossigil** [comment]
Unit tests fail

**Comment by ravivos** [comment]
tests fail
